-- Licence for this file and translations: CC0

return {
	-- core
	{"air",						"Luft (Sie Schummler!)"},
	{"ignore",					"ignorieren (Sie Schummler!)"},

	-- boat
	{"boats:boat",					"Boot"},

	-- bedsf
	{"beds:bed",					"schlichtes Bett"},
	{"beds:fancy_bed",				"schickes Bett"},

	-- bones
	{"bones:bones",					"Knochen"},
	
	-- bucket
	{"bucket:bucket_empty",				"Eimer"},
	{"bucket:bucket_water",				"Eimer mit Wasser"},
	{"bucket:bucket_river_water",			"Eimer mit Flusswasser"},
	{"bucket:bucket_lava",				"Eimer mit Lava"},

	-- carts
	{"carts:brakerail",				"Bremsschiene"},
	{"carts:powerrail",				"Beschleunigungsschiene"},
	{"carts:cart",					"Lore"},
	
	-- default
	-- craftitems
	{"default:stick",				"Stock"},
	{"default:paper",				"Papier"},
	{"default:book",				"Buch"},
	{"default:book_written",			"Buch mit Text"},
	{"default:coal_lump",				"Kohleklumpen"},
	{"default:iron_lump",				"Eisenerzklumpen"},
	{"default:copper_lump",				"Kupfererzklumpen"},
	{"default:mese_crystal",			"Mesekristall"},
	{"default:gold_lump",				"Golderzklumpen"},
	{"default:tin_lump",				"Zinnerzklumpen"},
	{"default:diamond",				"Diamant"},
	{"default:clay_lump",				"Tonklumpen"},
	{"default:steel_ingot",				"Stahlbarren"},
	{"default:copper_ingot",			"Kupferbarren"},
	{"default:bronze_ingot",			"Bronzebarren"},
	{"default:gold_ingot",				"Goldbarren"},
	{"default:tin_ingot",				"Zinnbarren"},
	{"default:mese_crystal_fragment",		"Mesekristallfragment"},
	{"default:clay_brick",				"Tonziegel"},
	{"default:scorched_stuff",			"verbranntes Zeug"},
	{"default:obsidian_shard",			"Obsidiansplitter"},
	{"default:coral_skeleton",			"Korallenskelett"},
	{"default:coral_orange",			"orangefarbene Koralle"},
	{"default:coral_brown",				"braune Koralle"},
	-- nodes
	{"default:stone",				"Stein"},
	{"default:stone_block",				"Steinblock"},
	{"default:desert_stone",			"Wüstenstein"},
	{"default:desert_stone_block",			"Wüstensteinblock"},
	{"default:desert_cobble",			"Wüstenpflasterstein"},
	{"default:desert_sandstone",			"Wüstensandstein"},
	{"default:desert_sandstone_block",		"Wüstensandsteinblock"},
	{"default:desert_sandstone_brick",		"behauener Wüstensandstein"},
	{"default:stone_with_coal",			"Kohle in Stein"},
	{"default:stone_with_iron",			"Eisenerz in Stein"},
	{"default:stone_with_copper",			"Kupfererz in Stein"},
	{"default:stone_with_mese",			"Meseerz in Stein"},
	{"default:stone_with_gold",			"Golderz in Stein"},
	{"default:stone_with_diamond",			"Rohdiamant in Stein"},
	{"default:stone_with_tin",			"Zinnerz in Stein"},
	{"default:stonebrick",				"behauener Stein"},
	{"default:desert_stonebrick",			"behauener Wüstenstein"},
	{"default:dirt_with_grass",			"Erde mit Gras"},
	{"default:dirt_with_grass_footsteps",		"Erde mit Gras und Fußspuren"},
	{"default:dirt_with_rainforest_litter",		"Regenwalderde"},
	{"default:dirt_with_dry_grass",			"Erde mit trockenem Gras"},
	{"default:dirt_with_snow",			"Erde mit Schnee"},
	{"default:dirt",				"Erde"},
	{"default:sand",				"Sand"},
	{"default:desert_sand",				"Wüstensand"},
	{"default:gravel",				"Kies"},
	{"default:sandstone",				"Sandstein"},
	{"default:sandstone_block",			"Sandsteinblock"},
	{"default:sandstonebrick",			"behauener Sandstein"},
	{"default:silver_sand",				"Silbersand"},
	{"default:silver_sandstone",			"Silbersandstein"},
	{"default:silver_sandstone_block",		"Silbersandsteinblock"},
	{"default:silver_sandstone_brick",		"behauener Silbersandstein"},
	{"default:clay",				"Ton"},
	{"default:brick",				"Tonziegelblock"},
	{"default:tree",				"Baum"},
	{"default:jungletree",				"Dschungelbaum"},
	{"default:junglewood",				"Dschungelholz"},
	{"default:jungleleaves",			"Dschungelblätter"},
	{"default:junglesapling",			"Dschungelsetzling"},
	{"default:junglegrass",				"Dschungelgras"},
	{"default:leaves",				"Blätter"},
	{"default:cactus",				"Kaktus"},
	{"default:papyrus",				"Papyrus"},
	{"default:bookshelf",				"Bücherschrank"},
	{"default:glass",				"Glas"},
	{"default:fence_junglewood",			"Dschungelholzzaun"},
	{"default:fence_aspen_wood",			"Espenholzzaun"},
	{"default:fence_acacia_wood",			"Akazienholzzaun"},
	{"default:fence_pine_wood",			"Kiefernholzzaun"},
	{"default:fence_wood",				"Holzzaun"},
	{"default:rail",				"Schiene"},
	{"default:ladder",				"Leiter"},
	{"default:ladder_steel",			"Stahlleiter"},
	{"default:wood",				"Holzplanken"},
	{"default:cloud",				"Wolke"},
	{"default:water_flowing",			"fließendes Wasser"},
	{"default:water_source",			"Wasserquelle"},
	{"default:river_water_flowing",			"fließendes Flusswasser"},
	{"default:river_water_source",			"Flusswasserquelle"},
	{"default:lava_flowing",			"fließende Lava"},
	{"default:lava_source",				"Lavaquelle"},
	{"default:torch",				"Fackel"},
	{"default:sign_wall",				"Schild"},
	{"default:chest",				"Truhe"},
	{"default:chest_locked",			"verschlossene Truhe"},
	{"default:furnace",				"Ofen"},
	{"default:furnace_active",			"Ofen"},
	{"default:cobble",				"Pflasterstein"},
	{"default:mossycobble",				"bemooster Pflasterstein"},
	{"default:coalblock",				"Kohleblock"},
	{"default:steelblock",				"Stahlblock"},
	{"default:copperblock",				"Kupferblock"},
	{"default:bronzeblock",				"Bronzeblock"},
	{"default:tinblock",				"Zinnblock"},
	{"default:mese",				"Mese"},
	{"default:goldblock",				"Goldblock"},
	{"default:diamondblock",			"Diamantblock"},
	{"default:obsidian_glass",			"Obsidianglas"},
	{"default:obsidian",				"Obsidian"},
	{"default:obsidian_block",			"Obsidianblock"},
	{"default:obsidianbrick",			"behauener Obsidian"},
	{"default:nyancat",				"Mieze-Maunze"},
	{"default:nyancat_rainbow",			"Regenbogen"},
	{"default:sapling",				"Setzling"},
	{"default:apple",				"Apfel"},
	{"default:dry_shrub",				"Trockenbusch"},
	{"default:grass_1",				"Gras"},
	{"default:grass_2",				"Gras"},
	{"default:grass_3",				"Gras"},
	{"default:grass_4",				"Gras"},
	{"default:grass_5",				"Gras"},
	{"default:dry_grass_1",				"trockenes Gras"},
	{"default:dry_grass_2",				"trockenes Gras"},
	{"default:dry_grass_3",				"trockenes Gras"},
	{"default:dry_grass_4",				"trockenes Gras"},
	{"default:dry_grass_5",				"trockenes Gras"},
	{"default:ice",					"Eis"},
	{"default:snow",				"Schnee"},
	{"default:snowblock",				"Schneeblock"},
	{"default:pine_needles",			"Kiefernadeln"},
	{"default:pine_sapling",			"Kiefersetzling"},
	{"default:pinetree",				"Kieferbaum"},
	{"default:pinewood",				"Kieferholzplanken"},
	{"default:acacia_bush_leaves",			"Akazienbuschblätter"},
	{"default:acacia_bush_sapling",			"Akazienbuschsetzling"},
	{"default:acacia_bush_stem",			"Akazienbuschstamm"},
	{"default:acacia_leaves",			"Akazienblätter"},
	{"default:acacia_sapling",			"Akaziensetzling"},
	{"default:acacia_tree",				"Akazienbaum"},
	{"default:acacia_wood",				"Akazienholzplanken"},
	{"default:aspen_leaves",			"Espenblätter"},
	{"default:aspen_sapling",			"Espensetzling"},
	{"default:aspen_tree",				"Espenbaum"},
	{"default:aspen_wood",				"Espenholzplanken"},
	{"default:bush_leaves",				"Buschblätter"},
	{"default:bush_sapling",			"Buschsetzling"},
	{"default:bush_stem",				"Buschstamm"},
	{"default:meselamp",				"Meselampe"},
	{"default:mese_post_light",			"Mesepostenbeleuchtung"},
	-- tools
	{"default:pick_wood",				"Holzspitzhacke"},
	{"default:pick_stone",				"Steinspitzhacke"},
	{"default:pick_bronze",				"Bronzespitzhacke"},
	{"default:pick_steel",				"Stahlspitzhacke"},
	{"default:pick_mese",				"Mesespitzhacke"},
	{"default:pick_diamond",			"Diamantspitzhacke"},
	{"default:shovel_wood",				"Holzschaufel"},
	{"default:shovel_stone",			"Steinschaufel"},
	{"default:shovel_bronze",			"Bronzeschaufel"},
	{"default:shovel_steel",			"Stahlschaufel"},
	{"default:shovel_mese",				"Meseschaufel"},
	{"default:shovel_diamond",			"Diamantschaufel"},
	{"default:axe_wood",				"Holzaxt"},
	{"default:axe_stone",				"Steinaxt"},
	{"default:axe_bronze",				"Bronzeaxt"},
	{"default:axe_steel",				"Stahlaxt"},
	{"default:axe_mese",				"Meseaxt"},
	{"default:axe_diamond",				"Diamantaxt"},
	{"default:sword_wood",				"Holzschwert"},
	{"default:sword_stone",				"Steinschwert"},
	{"default:sword_bronze",			"Bronzeschwert"},
	{"default:sword_steel",				"Stahlschwert"},
	{"default:sword_mese",				"Meseschwert"},
	{"default:sword_diamond",			"Diamantschwert"},
	{"default:skeleton_key",			"Skelettschlüssel"},
	
	-- doors
	{"doors:door_wood",				"Holztür"},
	{"doors:door_steel",				"Stahltür"},
	{"doors:door_glass",				"Glastür"},
	{"doors:door_obsidian_glass",			"Obsidianglastür"},
	{"doors:trapdoor",				"Falltür"},
	{"doors:trapdoor_steel",			"Stahlfalltür"},
	{"doors:gate_junglewood_closed",		"Dschungelholzzauntür"},
	{"doors:gate_aspen_wood_closed",		"Espenholzzauntür"},
	{"doors:gate_acacia_wood_closed",		"Akazienholzzauntür"},
	{"doors:gate_pine_wood_closed",			"Kiefernholzzauntür"},
	{"doors:gate_wood_closed",			"Holzzauntür"},
	
	-- dye
	{"dye:white",					"weißer Farbstoff"},
	{"dye:grey",					"grauer Farbstoff"},
	{"dye:dark_grey",				"dunkelgrauer Farbstoff"},
	{"dye:black",					"schwarzer Farbstoff"},
	{"dye:violet",					"lila Farbstoff"},
	{"dye:blue",					"blauer Farbstoff"},
	{"dye:cyan",					"türkiser Farbstoff"},
	{"dye:dark_green",				"dunkelgrüner Farbstoff"},
	{"dye:green",					"grüner Farbstoff"},
	{"dye:yellow",					"gelber Farbstoff"},
	{"dye:brown",					"brauner Farbstoff"},
	{"dye:orange",					"orange Farbstoff"},
	{"dye:red",					"roter Farbstoff"},
	{"dye:magenta",					"magenta Farbstoff"},
	{"dye:pink",					"rosa Farbstoff"},
	
	-- farming
	{"farming:straw",				"Stroh"},
	{"farming:soil",				"Ackerboden"},
	{"farming:soil_wet",				"Nasser Ackerboden"},
	{"farming:cotton",				"Faden"},
	{"farming:cotton_1",				"Baumwollpflanze"},
	{"farming:cotton_2",				"Baumwollpflanze"},
	{"farming:cotton_3",				"Baumwollpflanze"},
	{"farming:cotton_4",				"Baumwollpflanze"},
	{"farming:cotton_5",				"Baumwollpflanze"},
	{"farming:sting",				"Faden"},
	{"farming:hoe_wood",				"Holzhacke"},
	{"farming:hoe_stone",				"Steinhacke"},
	{"farming:hoe_steel",				"Stahlhacke"},
	{"farming:hoe_bronze",				"Bronzehacke"},
	{"farming:hoe_mese",				"Mesehacke"},
	{"farming:hoe_diamond",				"Diamanthacke"},
	{"farming:seed_wheat",				"Weizensaat"},
	{"farming:seed_cotton",				"Baumwollsaat"},
	{"farming:wheat",				"Weizen"},
	{"farming:wheat_1",				"Weizen"},
	{"farming:wheat_2",				"Weizen"},
	{"farming:wheat_3",				"Weizen"},
	{"farming:wheat_4",				"Weizen"},
	{"farming:wheat_5",				"Weizen"},
	{"farming:wheat_6",				"Weizen"},
	{"farming:wheat_7",				"Weizen"},
	{"farming:wheat_8",				"Weizen"},
	{"farming:flour",				"Mehl"},
	{"farming:bread",				"Brot"},
	
	-- fire
	{"fire:basic_flame",				"Feuer"},
	{"fire:permanent_flame",			"permanentes Feuer"},
	{"fire:flint_and_steel",			"Feuerstein und Stahl"},
	
	-- flowers
	{"flowers:dandelion_white",			"Pusteblume"},
	{"flowers:dandelion_yellow",			"Löwenzahn"},
	{"flowers:geranium",				"Geranie"},
	{"flowers:rose",				"Rose"},
	{"flowers:tulip",				"Tulpe"},
	{"flowers:viola",				"Veilchen"},
	{"flowers:mushroom_red",			"roter Pilz"},
	{"flowers:mushroom_brown",			"brauner Pilz"},
	{"flowers:mushroom_spores_red",			"rote Pilzsporen"},
	{"flowers:mushroom_spores_brown",		"braune Pilzsporen"},
	{"flowers:waterlily",				"Seerose"},
	
	-- nodetest
	{"nodetest:bone",				"Knochen"},
	{"nodetest:rock",				"Felsen"},
	{"nodetest:tree_horizontal",			"liegender Baum"},
	{"nodetest:jungletree_horizontal",		"liegender Dschungelbaum"},
	{"nodetest:papyrus_roots",			"Papyruswurzeln"},
	{"nodetest:conifersapling",			"Kiefensetzling"},
	{"nodetest:conifertree",			"Kiefernstamm"},
	{"nodetest:coniferleaves_1",			"Kiefernnadeln"},
	{"nodetest:coniferleaves_2",			"Kiefernnadeln"},
	{"nodetest:conifertree_horizontal",		"liegender Kiefernstamm"},
	{"nodetest:spearwood",				"Speer aus Holz"},
	{"nodetest:spearstone",				"Speer mit Steinspitze"},
	
	-- pots
	{"pots:pot",					"Blumentopf"},
	{"pots:cactus",					"Kaktus"},
	{"pots:dandelion_white",			"Pusteblume"},
	{"pots:dandelion_yellow",			"Löwenzahn"},
	{"pots:geranium",				"Geranie"},
	{"pots:rose",					"Rose"},
	{"pots:tulip",					"Tulpe"},
	{"pots:viola",					"Veilchen"},
	
	-- screwdriver
	{"screwdriver:screwdriver",			"Schraubendreher"},

	-- stairs
	{"stairs:stair_ice",				"Eistreppe"},
	{"stairs:stair_snowblock",			"Schneeblocktreppe"},
	{"stairs:stair_wood",				"Holztreppe"},
	{"stairs:stair_junglewood",			"Dschungelholztreppe"},
	{"stairs:stair_pinewood",			"Kieferholztreppe"},
	{"stairs:stair_acacia_wood",			"Akazienholztreppe"},
	{"stairs:stair_aspen_wood",			"Espenholztreppe"},
	{"stairs:stair_stone",				"Steintreppe"},
	{"stairs:stair_stone_block",			"Steinblocktreppe"},
	{"stairs:stair_mossycobble",			"bemooste Pflastersteintreppe"},
	{"stairs:stair_cobble",				"Pflastersteintreppe"},
	{"stairs:stair_stonebrick",			"behauene Steintreppe"},
	{"stairs:stair_silver_sandstone",		"Silbersandsteintreppe"},
	{"stairs:stair_silver_sandstone_block",		"Silbersandsteinblocktreppe"},
	{"stairs:stair_silver_sandstone_brick",		"behauene Silbersandsteintreppe"},
	{"stairs:stair_sandstone",			"Sandsteintreppe"},
	{"stairs:stair_sandstone_block",		"Sandsteinblocktreppe"},
	{"stairs:stair_sandstonebrick",			"behauene Sandsteintreppe"},
	{"stairs:stair_brick",				"Tonziegeltreppe"},
	{"stairs:stair_desert_sandstone",		"Wüstensandsteintreppe"},
	{"stairs:stair_desert_sandstone_block",		"Wüstensandsteinblocktreppe"},
	{"stairs:stair_desert_sandstone_brick",		"behauene Wüstensandsteintreppe"},
	{"stairs:stair_desert_stone",			"Wüstensteintreppe"},
	{"stairs:stair_desert_stone_block",		"Wüstensteinblocktreppe"},
	{"stairs:stair_desert_cobble",			"Wüstenpflastersteintreppe"},
	{"stairs:stair_desert_stonebrick",		"behauene Wüstensteintreppe"},
	{"stairs:stair_obsidian",			"Obsidiantreppe"},
	{"stairs:stair_obsidian_block",			"Obsidianblocktreppe"},
	{"stairs:stair_obsidianbrick",			"behauene Obsidiantreppe"},
	{"stairs:stair_straw",				"Strohtreppe"},
	{"stairs:stair_steelblock",			"Stahlblocktreppe"},
	{"stairs:stair_copperblock",			"Kupferblocktreppe"},
	{"stairs:stair_bronzeblock",			"Bronzeblocktreppe"},
	{"stairs:stair_goldblock",			"Goldblocktreppe"},

	{"stairs:slab_ice",				"Eisplatte"},
	{"stairs:slab_snowblock",			"Schneeblockplatte"},
	{"stairs:slab_wood",				"Holzplatte"},
	{"stairs:slab_junglewood",			"Dschungelholzplatte"},
	{"stairs:slab_pinewood",			"Kieferholzplatte"},
	{"stairs:slab_aspen_wood",			"Espenholzplatte"},
	{"stairs:slab_acacia_wood",			"Akazienholzplatte"},
	{"stairs:slab_stone",				"Steinplatte"},
	{"stairs:slab_stone_block",			"Steinblockplatte"},
	{"stairs:slab_cobble",				"Pflastersteinplatte"},
	{"stairs:slab_mossycobble",			"bemooste Pflastersteinplatte"},
	{"stairs:slab_stonebrick",			"behauene Steinplatte"},
	{"stairs:slab_silver_sandstone",		"Silbersandsteinplatte"},
	{"stairs:slab_silver_sandstone_block",		"Silbersandsteinblockplatte"},
	{"stairs:slab_silver_sandstone_brick",		"behauene Silbersandsteinplatte"},
	{"stairs:slab_sandstone",			"Sandsteinplatte"},
	{"stairs:slab_sandstone_block",			"Sandsteinblockplatte"},
	{"stairs:slab_sandstonebrick",			"behauene Sandsteinplatte"},
	{"stairs:slab_brick",				"Tonziegelplatte"},
	{"stairs:slab_desert_stone",			"Wüstensteinplatte"},
	{"stairs:slab_desert_stone_block",		"Wüstensteinblockplatte"},
	{"stairs:slab_desert_sandstone",		"Wüstensandsteinplatte"},
	{"stairs:slab_desert_sandstone_block",		"Wüstensandsteinblockplatte"},
	{"stairs:slab_desert_sandstone_brick",		"behauene Wüstensandsteinplatte"},
	{"stairs:slab_desert_cobble",			"Wüstenpflastersteinplatte"},
	{"stairs:slab_desert_stonebrick",		"behauene Wüstensteinplatte"},
	{"stairs:slab_obsidian",			"Obsidianplatte"},
	{"stairs:slab_obsidian_block",			"Obsidianblockplatte"},
	{"stairs:slab_obsidianbrick",			"behauene Obsidianplatte"},
	{"stairs:slab_straw", 				"Strohplatte"},
	{"stairs:slab_steelblock",			"Stahlblockplatte"},
	{"stairs:slab_copperblock",			"Kupferblockplatte"},
	{"stairs:slab_bronzeblock",			"Bronzeblockplatte"},
	{"stairs:slab_goldblock", 			"Goldblockplatte"},

	-- tnt
	{"tnt:tnt",					"TNT"},
	{"tnt:gunpowder",				"Schießpulver"},
	
	-- wool
	{"wool:white",					"weiße Wolle"},
	{"wool:grey",					"graue Wolle"},
	{"wool:dark_grey",				"dunkelgraue Wolle"},
	{"wool:black",					"schwarze Wolle"},
	{"wool:violet",					"lila Wolle"},
	{"wool:blue",					"blaue Wolle"},
	{"wool:cyan",					"türkise Wolle"},
	{"wool:dark_green",				"dunkelgrüne Wolle"},
	{"wool:green",					"grüne Wolle"},
	{"wool:yellow",					"gelbe Wolle"},
	{"wool:brown",					"braune Wolle"},
	{"wool:orange",					"orange Wolle"},
	{"wool:red",					"rote Wolle"},
	{"wool:magenta",				"magenta Wolle"},
	{"wool:pink",					"rosa Wolle"},

	-- vessels
	{"vessels:glass_bottle",			"Glasflasche"},
	{"vessels:drinking_glass",			"Trinkglas"},
	{"vessels:steel_bottle",			"Stahlflasche"},
	{"vessels:glass_fragments",			"Glasscherben"},
	{"vessels:shelf",				"Gefäßschrank"},

	-- walls
	{"walls:cobble",				"Pflastersteinmauer"},
	{"walls:mossycobble",				"bemooste Pflastersteinmauer"},
	{"walls:desertcobble",				"Wüstenpflastersteinmauer"},

	-- xpanes
	{"xpanes:bar_flat",				"Eisenstäbe"},
	{"xpanes:pane_flat",				"Glasscheibe"},
}

