vortoj = {
	-- bones
	{"bones:bones",					"Knochen"},
	
	-- bucket
	{"bucket:bucket_empty",				"Eimer"},
	{"bucket:bucket_water",				"Eimer Wasser"},
	{"bucket:bucket_lava",				"Eimer Lava"},
	
	-- default
	-- craftitems
	{"default:stick",					"Stock"},
	{"default:paper",					"Papier"},
	{"default:book",					"Buch"},
	{"default:coal_lump",				"Kohle"},
	{"default:iron_lump",				"Eisenerz"},
	{"default:copper_lump",				"Kupfererz"},
	{"default:mese_crystal",				"Mese-Kristall"},
	{"default:clay_lump",				"Ton"},
	{"default:steel_ingot",				"Stahlbarren"},
	{"default:copper_ingot",				"Kupferbarren"},
	{"default:mese_crystal_fragment",		"Fragment eines Mese-Kristalls"},
	{"default:clay_brick",				"Tonziegel"},
	{"default:scorched_stuff",			"Verbranntes Zeug"},
	-- nodes
	{"default:stone",					"Stein"},
	{"default:desert_stone",				"Wüsten Stein"},
	{"default:stone_with_coal",			"Kohle"},
	{"default:stone_with_iron",			"Eisenerz"},
	{"default:stone_with_copper",			"Kupfererz"},
	{"default:stone_with_mese",			"Meseerz"},
	{"default:dirt_with_grass",			"Erde mit Gras"},
	{"default:dirt_with_grass_footsteps",	"Erde mit Gras und Fußspuren"},
	{"default:dirt_with_snow",			"Erde mit Schnee"},
	{"default:dirt",					"Erde"},
	{"default:sand",					"Sand"},
	{"default:desert_sand",				"Wüstensand"},
	{"default:gravel",					"Kies"},
	{"default:sandstone",				"Sandstein"},
	{"default:clay",					"Ton"},
	{"default:brick",					"Ziegel"},
	{"default:tree",					"Baum"},
	{"default:jungletree",				"Dschungel Baum"},
	{"default:jungleleaves",				"Dschungel Blätter"},
	{"default:junglesapling",			"Dschungel Steckling"},
	{"default:junglegrass",				"Dschungel Gras"},
	{"default:leaves",					"Blätter"},
	{"default:cactus",					"Kaktus"},
	{"default:papyrus",					"Papyrus"},
	{"default:bookshelf",				"Bücherschrank"},
	{"default:glass",					"Glas"},
	{"default:fence_wood",				"Holzzaun"},
	{"default:rail",					"Schiene"},
	{"default:ladder",					"Leiter"},
	{"default:wood",					"Holz"},
	{"default:cloud",					"Wolke"},
	{"default:water_flowing",			"Fließendes Wasser"},
	{"default:water_source",				"Wasser Quelle"},
	{"default:lava_flowing",				"Fließende Lava"},
	{"default:lava_source",				"Lava Quelle"},
	{"default:torch",					"Fackel"},
	{"default:sign_wall",				"Schild"},
	{"default:chest",					"Kiste"},
	{"default:chest_locked",				"Verschlossene Kiste"},
	{"default:furnace",					"Ofen"},
	{"default:furnace_active",			"Ofen"},
	{"default:cobble",					"Pflasterstein"},
	{"default:mossycobble",				"Pflasterstein mit Moos"},
	{"default:coalblock",				"Kohleblock"},
	{"default:steelblock",				"Stahlblock"},
	{"default:copperblock",				"Kupferblock"},
	{"default:mese",					"Mese"},
	{"default:nyancat",					"Nyan Cat"},
	{"default:nyancat_rainbow",			"Regenbogen"},
	{"default:sapling",					"Steckling"},
	{"default:apple",					"Apfel"},
	{"default:dry_shrub",				"Gestrüpp"},
	{"default:grass_1",					"Gras"},
	{"default:grass_2",					"Gras"},
	{"default:grass_3",					"Gras"},
	{"default:grass_4",					"Gras"},
	{"default:grass_5",					"Gras"},
	{"default:ice",					"Eis"},
	{"default:snow",					"Schnee"},
	{"default:snowblock",				"Schneeblock"},
	-- tools
	{"default:pick_wood",				"Hölzerne Spitzhacke"},
	{"default:pick_stone",				"Steinerne Spitzhacke"},
	{"default:pick_copper",				"Kupferne Spitzhacke"},
	{"default:pick_steel",				"Stählerne Spitzhacke"},
	{"default:pick_mese",				"Mese Spitzhacke"},
	{"default:shovel_wood",				"Hölzerne Schaufel"},
	{"default:shovel_stone",				"Steinerne Schaufel"},
	{"default:shovel_copper",			"Kupferne Schaufel"},
	{"default:shovel_steel",				"Stählerne Schaufel"},
	{"default:axe_wood",				"Hölzerne Axt"},
	{"default:axe_stone",				"Steinerne Axt"},
	{"default:axe_copper",				"Kupferne Axt"},
	{"default:axe_steel",				"Stählerne Axt"},
	{"default:sword_wood",				"Holzschwert"},
	{"default:sword_stone",				"Steinschwert"},
	{"default:sword_copper",				"Kupferschwert"},
	{"default:sword_steel",				"Stahlschwert"},
	
	-- doors
	{"doors:door_wood",					"Holztür"},
	{"doors:door_steel",				"Stahltür"},
	
	-- dye
	{"dye:white",						"Weiße Farbe"},
	{"dye:grey",						"Graue Farbe"},
	{"dye:dark_grey",					"Dunkelgraue Farbe"},
	{"dye:black",						"Schwarze Farbe"},
	{"dye:violet",						"Lila Farbe"},
	{"dye:blue",						"Blaue Farbe"},
	{"dye:cyan",						"Zyane Farbe"},
	{"dye:dark_green",					"Dunkelgrüne Farbe"},
	{"dye:green",						"Grüne Farbe"},
	{"dye:yellow",						"Gelbe Farbe"},
	{"dye:brown",						"Braune Farbe"},
	{"dye:orange",						"Orange Farbe"},
	{"dye:red",						"Rote Farbe"},
	{"dye:magenta",					"Magentae Farbe"},
	{"dye:pink",						"Pinke Farbe"},
	
	-- farming
	{"farming:cotton",					"Baumwolle"},
	{"farming:cotton_1",				"Baumwollpflanze"},
	{"farming:cotton_2",				"Baumwollpflanze"},
	{"farming:cotton_3",				"Baumwollpflanze"},
	{"farming:cotton_4",				"Baumwollpflanze"},
	{"farming:cotton_5",				"Baumwollpflanze"},
	{"farming:sting",					"Faden"},
	{"farming:hoe_wood",				"Hölzerne Hacke"},
	{"farming:hoe_stone",				"Steinerne Hacke"},
	{"farming:hoe_steel",				"Stählerne Hacke"},
	{"farming:hoe_mese",				"Mese Hacke"},
	{"farming:weed",					"Unkraut"},
	{"farming:wheat",					"Weizen"},
	{"farming:wheat_1",					"Weizen"},
	{"farming:wheat_2",					"Weizen"},
	{"farming:wheat_3",					"Weizen"},
	{"farming:wheat_4",					"Weizen"},
	{"farming:wheat_5",					"Weizen"},
	{"farming:wheat_6",					"Weizen"},
	{"farming:wheat_7",					"Weizen"},
	{"farming:wheat_8",					"Weizen"},
	{"farming:flour",					"Mehl"},
	{"farming:dough",					"Teig"},
	{"farming:bread",					"Brot"},
	
	-- fire
	{"fire:basic_flame",				"Feuer"},
	
	-- flowers
	{"flowers:dandelion_white",			"Pusteblume"},
	{"flowers:dandelion_yellow",			"Löwenzahn"},
	{"flowers:geranium",				"Geranie"},
	{"flowers:rose",					"Rose"},
	{"flowers:tulip",					"Tulpe"},
	{"flowers:viola",					"Veilchen"},
	
	-- nodetest
	{"nodetest:bone",					"Knochen"},
	{"nodetest:desert_sandstone",			"Wüstensandstein"},
	{"nodetest:rock",					"Felsen"},
	{"nodetest:tree_horizontal",			"Baum liegend"},
	{"nodetest:jungletree_horizontal",		"Dschungelbaum liegend"},
	{"nodetest:papyrus_roots",			"Papyrus Wurzeln"},
	{"nodetest:conifersapling",			"Kiefen Steckling"},
	{"nodetest:conifertree",				"Kieferstamm"},
	{"nodetest:coniferleaves_1",			"Kiefernadeln"},
	{"nodetest:coniferleaves_2",			"Kiefernadeln"},
	{"nodetest:conifertree_horizontal",	"Kieferstamm liegend"},
	{"nodetest:spearwood",				"Speer aus Holz"},
	{"nodetest:spearstone",				"Speer mit Steinspitze"},
	
	-- pots
	{"pots:pot",						"Blumentopf"},
	{"pots:cactus",					"Kaktus"},
	{"pots:dandelion_white",				"Pusteblume"},
	{"pots:dandelion_yellow",			"Löwenzahn"},
	{"pots:geranium",					"Geranie"},
	{"pots:rose",						"Rose"},
	{"pots:tulip",						"Tulpe"},
	{"pots:viola",						"Veilchen"},
	{"pots:viola",						"Setzlinge"},
	
	-- screwdriver
	{"screwdriver:screwdriver",			"Schraubendreher"},
	{"screwdriver:screwdriver_1",			"Schraubendreher Modus 1"},
	{"screwdriver:screwdriver_2",			"Schraubendreher Modus 2"},
	{"screwdriver:screwdriver_3",			"Schraubendreher Modus 3"},
	{"screwdriver:screwdriver_4",			"Schraubendreher Modus 4"},
	
	-- wool
	{"wool:white",						"Weiße Wolle"},
	{"wool:grey",						"Graue Wolle"},
	{"wool:dark_grey",					"Dunkelgraue Wolle"},
	{"wool:black",						"Schwarze Wolle"},
	{"wool:violet",					"Lila Wolle"},
	{"wool:blue",						"Blaue Wolle"},
	{"wool:cyan",						"Zyane Wolle"},
	{"wool:dark_green",					"Dunkelgrüne Wolle"},
	{"wool:green",						"Grüne Wolle"},
	{"wool:yellow",					"Gelbe Wolle"},
	{"wool:brown",						"Braune Wolle"},
	{"wool:orange",					"Orange Wolle"},
	{"wool:red",						"Rote Wolle"},
	{"wool:magenta",					"Magentae Wolle"},
	{"wool:pink",						"Pinke Wolle"},
}
