vortoj = {
	-- Boats
	{"boats:boat",					""},
	
	-- bones
	{"bones:bones",					"Knochen"},
	
	-- bucket
	{"bucket:bucket_empty",				"Eimer"},
	{"bucket:bucket_water",				"Eimer Wasser"},
	{"bucket:bucket_lava",				"Eimer Lava"},
	
	-- default
	-- craftitems
	{"default:stick",					"Stock"},
	{"default:paper",					"Papier"},
	{"default:book",					"Buch"},
	{"default:coal_lump",				"Kohle"},
	{"default:iron_lump",				"Eisenerz"},
	{"default:copper_lump",				"Kupfererz"},
	{"default:mese_crystal",				"Mese-Kristall"},
	{"default:gold_lump",				"Golderz"},
	{"default:diamond",					"Diamant"},
	{"default:clay_lump",				"Ton"},
	{"default:steel_ingot",				"Stahlbarren"},
	{"default:copper_ingot",				"Kupferbarren"},
	{"default:bronze_ingot",				"Bronzebarren"},
	{"default:gold_ingot",				"Goldbarren"},
	{"default:mese_crystal_fragment",		"Fragment eines Mese-Kristalls"},
	{"default:clay_brick",				"Tonziegel"},
	{"default:scorched_stuff",			"Verbranntes Zeug"},
	{"default:obsidian_shard",			"Obsidiansplitter"},
	-- nodes
	{"default:stone",					"Stein"},
	{"default:desert_stone",				"Wustenstein"},
	{"default:stone_with_coal",			"Kohle"},
	{"default:stone_with_iron",			"Eisenerz in Stein"},
	{"default:stone_with_copper",			"Kupfererz in Stein"},
	{"default:stone_with_mese",			"Meseerz in Stein"},
	{"default:stone_with_gold",			"Golderz in Stein"},
	{"default:stone_with_diamond",		"Rohdiamant in Stein"},
	{"default:stone_stonebrick",			"Behauener Stein"},
	{"default:stone_desert_stonebrick",	"Behauener Wustenstein"},
	{"default:dirt_with_grass",			"Erde mit Gras"},
	{"default:dirt_with_grass_footsteps",	"Erde mit Gras und Fusspuren"},
	{"default:dirt_with_snow",			"Erde mit Schnee"},
	{"default:dirt",					"Erde"},
	{"default:sand",					"Sand"},
	{"default:desert_sand",				"Wustensand"},
	{"default:gravel",					"Kies"},
	{"default:sandstone",				"Sandstein"},
	{"default:sandstonebrick",			"Behauener Sandstein"},
	{"default:clay",					"Ton"},
	{"default:brick",					"Ziegel"},
	{"default:tree",					"Baum"},
	{"default:jungletree",				"Dschungel Baum"},
	{"default:junglewood",				"Dschungel Holz"},
	{"default:jungleleaves",				"Dschungel Blatter"},
	{"default:junglesapling",			"Dschungel Steckling"},
	{"default:junglegrass",				"Dschungel Gras"},
	{"default:leaves",					"Blatter"},
	{"default:cactus",					"Kaktus"},
	{"default:papyrus",					"Papyrus"},
	{"default:bookshelf",				"Bucherschrank"},
	{"default:glass",					"Glas"},
	{"default:fence_wood",				"Holzzaun"},
	{"default:rail",					"Schiene"},
	{"default:ladder",					"Leiter"},
	{"default:wood",					"Holz"},
	{"default:cloud",					"Wolke"},
	{"default:water_flowing",			"Fliesendes Wasser"},
	{"default:water_source",				"Wasser Quelle"},
	{"default:lava_flowing",				"Fliesende Lava"},
	{"default:lava_source",				"Lava Quelle"},
	{"default:torch",					"Fackel"},
	{"default:sign_wall",				"Schild"},
	{"default:chest",					"Kiste"},
	{"default:chest_locked",				"Verschlossene Kiste"},
	{"default:furnace",					"Ofen"},
	{"default:furnace_active",			"Ofen"},
	{"default:cobble",					"Pflasterstein"},
	{"default:mossycobble",				"Pflasterstein mit Moos"},
	{"default:coalblock",				"Kohleblock"},
	{"default:steelblock",				"Stahlblock"},
	{"default:copperblock",				"Kupferblock"},
	{"default:bronzeblock",				"Bronzeblock"},
	{"default:mese",					"Mese"},
	{"default:goldblock",				"Goldblock"},
	{"default:diamondblock",				"Diamantblock"},
	{"default:obsidian_glass",			"Obsidianglas"},
	{"default:obsidian",				"Obsidian"},
	{"default:nyancat",					"Mieze Maunze"},
	{"default:nyancat_rainbow",			"Regenbogen"},
	{"default:sapling",					"Steckling"},
	{"default:apple",					"Apfel"},
	{"default:dry_shrub",				"Gestrupp"},
	{"default:grass_1",					"Gras"},
	{"default:grass_2",					"Gras"},
	{"default:grass_3",					"Gras"},
	{"default:grass_4",					"Gras"},
	{"default:grass_5",					"Gras"},
	{"default:ice",					"Eis"},
	{"default:snow",					"Schnee"},
	{"default:snowblock",				"Schneeblock"},
	-- tools
	{"default:pick_bronze",					""},
	{"default:pick_diamond",				""},
	{"default:pick_wood",				"Holzerne Spitzhacke"},
	{"default:pick_stone",				"Steinerne Spitzhacke"},
	{"default:pick_copper",				"Kupferne Spitzhacke"},
	{"default:pick_steel",				"Stahlerne Spitzhacke"},
	{"default:pick_mese",				"Mese Spitzhacke"},
	{"default:shovel_bronze",				""},
	{"default:shovel_diamond",				""},
	{"default:shovel_mese",					""},
	{"default:shovel_wood",				"Holzerne Schaufel"},
	{"default:shovel_stone",				"Steinerne Schaufel"},
	{"default:shovel_copper",			"Kupferne Schaufel"},
	{"default:shovel_steel",				"Stahlerne Schaufel"},
	{"default:axe_bronze",					""},
	{"default:axe_diamond",					""},
	{"default:axe_mese",					""},
	{"default:axe_wood",				"Holzerne Axt"},
	{"default:axe_stone",				"Steinerne Axt"},
	{"default:axe_copper",				"Kupferne Axt"},
	{"default:axe_steel",				"Stahlerne Axt"},
	{"default:sword_bronze",				""},
	{"default:sword_diamond",				""},
	{"default:sword_mese",					""},
	{"default:sword_wood",				"Holzschwert"},
	{"default:sword_stone",				"Steinschwert"},
	{"default:sword_copper",				"Kupferschwert"},
	{"default:sword_steel",				"Stahlschwert"},
	
	-- doors
	{"doors:door_wood",					"Holztur"},
	{"doors:door_steel",				"Stahltur"},
	{"doors:door_glass",					""},
	{"doors:door_obsidian_glass",				""},
	{"doors:trapdoor",					""},
	
	-- dye
	{"dye:white",						"Weise Farbe"},
	{"dye:grey",						"Graue Farbe"},
	{"dye:dark_grey",					"Dunkelgraue Farbe"},
	{"dye:black",						"Schwarze Farbe"},
	{"dye:violet",						"Lila Farbe"},
	{"dye:blue",						"Blaue Farbe"},
	{"dye:cyan",						"Zyane Farbe"},
	{"dye:dark_green",					"Dunkelgrune Farbe"},
	{"dye:green",						"Grune Farbe"},
	{"dye:yellow",						"Gelbe Farbe"},
	{"dye:brown",						"Braune Farbe"},
	{"dye:orange",						"Orange Farbe"},
	{"dye:red",						"Rote Farbe"},
	{"dye:magenta",					"Magentae Farbe"},
	{"dye:pink",						"Pinke Farbe"},
	
	-- farming
	{"farming:soil",					"Ackerboden"},
	{"farming:soil_wet",				"Nasser Ackerboden"},
	{"farming:cotton",					"Baumwolle"},
	{"farming:sting",					"Faden"},
	{"farming:hoe_wood",				"Holzerne Hacke"},
	{"farming:hoe_stone",				"Steinerne Hacke"},
	{"farming:hoe_steel",				"Stahlerne Hacke"},
	{"farming:hoe_bronze",				"Bronzene Hacke"},
	{"farming:hoe_mese",				"Mese Hacke"},
	{"farming:weed",					"Unkraut"},
	{"farming:seed_wheat",				"Weizensaat"},
	{"farming:wheat",					"Weizen"},
	{"farming:flour",					"Mehl"},
	{"farming:dough",					"Teig"},
	{"farming:bread",					"Brot"},
	
	-- fire
	{"fire:basic_flame",				"Feuer"},
	
	-- flowers
	{"flowers:dandelion_white",			"Pusteblume"},
	{"flowers:dandelion_yellow",			"Lowenzahn"},
	{"flowers:geranium",				"Geranie"},
	{"flowers:rose",					"Rose"},
	{"flowers:tulip",					"Tulpe"},
	{"flowers:viola",					"Veilchen"},
	
	-- screwdriver
	{"screwdriver:screwdriver",			"Schraubendreher"},
	{"screwdriver:screwdriver1",			"Schraubendreher Modus 1"},
	{"screwdriver:screwdriver2",			"Schraubendreher Modus 2"},
	{"screwdriver:screwdriver3",			"Schraubendreher Modus 3"},
	{"screwdriver:screwdriver4",			"Schraubendreher Modus 4"},
	
	-- Stairs
	--Slab
	{"stairs:slab_wood",					""},
	{"stairs:slab_stone",					""},
	{"stairs:slab_cobble",					""},
	{"stairs:slab_desert_stone",				""},
	{"stairs:slab_desert_cobble",				""},
	{"stairs:slab_desert_stonebrick",			""},
	{"stairs:slab_brick",					""},
	{"stairs:slab_sandstone",				""},
	{"stairs:slab_sandstonebrick",				""},
	{"stairs:slab_junglewood",				""},
	{"stairs:slab_stonebrick",				""},
	--Stair
	{"stairs:stair_wood",					""},
	{"stairs:stair_stone",					""},
	{"stairs:stair_cobble",					""},
	{"stairs:stair_desert_stone",				""},
	{"stairs:stair_desert_cobble",				""},
	{"stairs:stair_desert_stonebrick",			""},
	{"stairs:stair_brick",					""},
	{"stairs:stair_sandstone",				""},
	{"stairs:stair_sandstonebrick",				""},
	{"stairs:stair_junglewood",				""},
	{"stairs:stair_stonebrick",				""},
	
	-- TNT
	{"tnt:tnt",					"TNT"},
	{"tnt:gunpowder",					""},
	
	-- vessels
	{"vessels:glass_bottle",				"Glasflasche"},
	{"vessels:drinking_glass",			"Trinkglas"},
	{"vessels:steel_bottle",				"Stahlflasche"},
	{"vessels:glass_fragments",			"Glasscherben"},
	
	-- wool
	{"wool:white",						"Weise Wolle"},
	{"wool:grey",						"Graue Wolle"},
	{"wool:dark_grey",					"Dunkelgraue Wolle"},
	{"wool:black",						"Schwarze Wolle"},
	{"wool:violet",					"Lila Wolle"},
	{"wool:blue",						"Blaue Wolle"},
	{"wool:cyan",						"Zyane Wolle"},
	{"wool:dark_green",					"Dunkelgrune Wolle"},
	{"wool:green",						"Grune Wolle"},
	{"wool:yellow",					"Gelbe Wolle"},
	{"wool:brown",						"Braune Wolle"},
	{"wool:orange",					"Orange Wolle"},
	{"wool:red",						"Rote Wolle"},
	{"wool:magenta",					"Magentae Wolle"},
	{"wool:pink",						"Pinke Wolle"},
	
	-- Xpanes
	{"xpanes:pane",					""},
	{"xpanes:bar",					""},
}
