vortoj.de = {
	-- bones
	{"bones:bones",					"Knochen"},
	
	-- bucket
	{"bucket:bucket_empty",				"Eimer"},
	{"bucket:bucket_water",				"Eimer Wasser"},
	{"bucket:bucket_lava",				"Eimer Lava"},
	
	-- default
	-- craftitems
	{"default:stick",					"Stock"},
	{"default:paper",					"Papier"},
	{"default:book",					"Buch"},
	{"default:coal_lump",				"Kohle"},
	{"default:iron_lump",				"Eisenerz"},
	{"default:copper_lump",				"Kupfererz"},
	{"default:mese_crystal",				"Mese-Kristall"},
	{"default:clay_lump",				"Ton"},
	{"default:steel_ingot",				"Stahlbarren"},
	{"default:copper_ingot",				"Kupferbarren"},
	{"default:mese_crystal_fragment",		"Fragment eines Mese-Kristalls"},
	{"default:clay_brick",				"Tonziegel"},
	{"default:scorched_stuff",			"Verbranntes Zeug"},
	-- nodes
	{"default:stone",					"Stein"},
	{"default:desert_stone",				"Wüsten Stein"},
	{"default:stone_with_coal",			"Kohle"},
	{"default:stone_with_iron",			"Eisenerz"},
	{"default:stone_with_copper",			"Kupfererz"},
	{"default:stone_with_mese",			"Meseerz"},
	{"default:dirt_with_grass",			"Erde mit Gras"},
	{"default:dirt_with_grass_footsteps",	"Erde mit Gras und Fußspuren"},
	{"default:dirt_with_snow",			"Erde mit Schnee"},
	{"default:dirt",					"Erde"},
	{"default:sand",					"Sand"},
	{"default:desert_sand",				"Wüstensand"},
	{"default:gravel",					"Kies"},
	{"default:sandstone",				"Sandstein"},
	{"default:clay",					"Ton"},
	{"default:brick",					"Ziegel"},
	{"default:tree",					"Baumstamm"},
	{"default:jungletree",				"Dschungel Baumstamm"},
	{"default:jungleleaves",				"Dschungel Blätter"},
	{"default:junglesapling",			"Dschungel Setzling"},
	{"default:junglegrass",				"Dschungel Gras"},
	{"default:leaves",					"Blätter"},
	{"default:cactus",					"Kaktus"},
	{"default:papyrus",					"Papyrus"},
	{"default:bookshelf",				"Bücherschrank"},
	{"default:glass",					"Glas"},
	{"default:fence_wood",				"Holzzaun"},
	{"default:rail",					"Schiene"},
	{"default:ladder",					"Leiter"},
	{"default:wood",					"Holz"},
	{"default:cloud",					"Wolke"},
	{"default:water_flowing",			"Fließendes Wasser"},
	{"default:water_source",				"Wasser Quelle"},
	{"default:lava_flowing",				"Fließende Lava"},
	{"default:lava_source",				"Lava Quelle"},
	{"default:torch",					"Fackel"},
	{"default:sign_wall",				"Schild"},
	{"default:chest",					"Kiste"},
	{"default:chest_locked",				"Verschlossene Kiste"},
	{"default:furnace",					"Ofen"},
	{"default:furnace_active",			"Ofen"},
}
