vortoj = {
	-- beds
	{"beds:bed",					"Cama"},

	-- bones
	{"bones:bones",					"Huesos"},
	
	-- bucket
	{"bucket:bucket_empty",				"Cubo vacío"},
	{"bucket:bucket_water",				"Cubo de agua"},
	{"bucket:bucket_lava",				"Cubo de lava"},

	-- carts
	{"carts:cart",					""},
	{"carts:powerrail",				""},
	{"carts:brakerail",				""},
	
	-- default
	-- craftitems
	{"default:stick",					"Palo"},
	{"default:paper",					"Papel"},
	{"default:book",					"Libro"},
	{"default:coal_lump",				""},
	{"default:iron_lump",				""},
	{"default:copper_lump",				""},
	{"default:mese_crystal",				""},
	{"default:gold_lump",				""},
	{"default:diamond",					"Diamante"},
	{"default:clay_lump",				""},
	{"default:steel_ingot",				""},
	{"default:copper_ingot",				""},
	{"default:bronze_ingot",				""},
	{"default:gold_ingot",				""},
	{"default:mese_crystal_fragment",		""},
	{"default:clay_brick",				"Ladrillo de arcilla"},
	{"default:scorched_stuff",			""},
	{"default:obsidian_shard",			""},
	-- nodes
	{"default:stone",					"Piedra"},
	{"default:desert_stone",				"Piedra del desierto"},
	{"default:stone_with_coal",			""},
	{"default:stone_with_iron",			"Piedra con hierro"},
	{"default:stone_with_copper",			"Piedra con cobre"},
	{"default:stone_with_mese",			""},
	{"default:stone_with_gold",			"Piedra con oro"},
	{"default:stone_with_diamond",		"Piedra con diamante"},
	{"default:stone_stonebrick",			""},
	{"default:stone_desert_stonebrick",	""},
	{"default:dirt_with_grass",			""},
	{"default:dirt_with_grass_footsteps",	""},
	{"default:dirt_with_snow",			""},
	{"default:dirt",					""},
	{"default:sand",					"Arena"},
	{"default:desert_sand",				"Arena del desierto"},
	{"default:gravel",					""},
	{"default:sandstone",				""},
	{"default:sandstonebrick",			""},
	{"default:clay",					"Arcilla"},
	{"default:brick",					"Ladrillo"},
	{"default:tree",					"Árbol"},
	{"default:jungletree",				"Árbol de la selva"},
	{"default:junglewood",				"Madera de la selva"},
	{"default:jungleleaves",				"Hojas de la selva"},
	{"default:junglesapling",			""},
	{"default:junglegrass",				"Hierba de la selva"},
	{"default:leaves",					"Hojas"},
	{"default:cactus",					"Cactus"},
	{"default:papyrus",					"Papiro"},
	{"default:bookshelf",				"Estantería"},
	{"default:glass",					"Cristal"},
	{"default:fence_wood",				""},
	{"default:rail",					"Raíl"},
	{"default:ladder",					"Escalera"},
	{"default:wood",					"Madera"},
	{"default:cloud",					"Nube"},
	{"default:water_flowing",			"Agua fluyendo"},
	{"default:water_source",				"Origen del agua"},
	{"default:lava_flowing",				"Lava fluyendo"},
	{"default:lava_source",				"Origen de la lava"},
	{"default:torch",					"Antorcha"},
	{"default:sign_wall",				""},
	{"default:chest",					""},
	{"default:chest_locked",				""},
	{"default:furnace",					""},
	{"default:furnace_active",			""},
	{"default:cobble",					""},
	{"default:mossycobble",				""},
	{"default:coalblock",				""},
	{"default:steelblock",				""},
	{"default:copperblock",				""},
	{"default:bronzeblock",				""},
	{"default:mese",					""},
	{"default:goldblock",				""},
	{"default:diamondblock",				""},
	{"default:obsidian_glass",			"Cristal de obsidiana"},
	{"default:obsidian",				"Obsidiana"},
	{"default:nyancat",					""},
	{"default:nyancat_rainbow",			""},
	{"default:sapling",					""},
	{"default:apple",					"Manzana"},
	{"default:dry_shrub",				""},
	{"default:grass_1",					"Hierba 1"},
	{"default:grass_2",					"Hierba 2"},
	{"default:grass_3",					"Hierba 3"},
	{"default:grass_4",					"Hierba 4"},
	{"default:grass_5",					"Hierba 5"},
	{"default:ice",					"Hielo"},
	{"default:snow",					"Nieve"},
	{"default:snowblock",				"Bloque de nieve"},
	-- tools
	{"default:pick_wood",				""},
	{"default:pick_stone",				""},
	{"default:pick_copper",				""},
	{"default:pick_steel",				""},
	{"default:pick_mese",				""},
	{"default:shovel_wood",				""},
	{"default:shovel_stone",				""},
	{"default:shovel_copper",			""},
	{"default:shovel_steel",				""},
	{"default:axe_wood",				""},
	{"default:axe_stone",				""},
	{"default:axe_copper",				""},
	{"default:axe_steel",				""},
	{"default:sword_wood",				"Espada de madera"},
	{"default:sword_stone",				"Espada de piedra"},
	{"default:sword_copper",				"Espada de cobre"},
	{"default:sword_steel",				"Espada de acero"},
	
	-- doors
	{"doors:door_wood",					"Puerta de madera"},
	{"doors:door_steel",				"Puerta de acero"},
	
	-- dye
	{"dye:white",						"Tinte blanco"},
	{"dye:grey",						"Tinte gris"},
	{"dye:dark_grey",					"Tinte gris oscuro"},
	{"dye:black",						"Tinte negro"},
	{"dye:violet",						"Tinte morado"},
	{"dye:blue",						"Tinte azul"},
	{"dye:cyan",						"Tinte azul celeste"},
	{"dye:dark_green",					"Tinte verde oscuro"},
	{"dye:green",						"Tinte verde"},
	{"dye:yellow",						"Tinte amarillo"},
	{"dye:brown",						"Tinte marrón"},
	{"dye:orange",						"Tinte naranja"},
	{"dye:red",						"Tinte rojo"},
	{"dye:magenta",					"Tinte magenta"},
	{"dye:pink",						"Tinte rosa"},
	
	-- farming
	{"farming:soil",					""},
	{"farming:soil_wet",				""},
	{"farming:seed_cotton",				""},
	{"farming:cotton",					"Algodón"},
	{"farming:cotton_1",				"Algodón 1"},
	{"farming:cotton_2",				"Algodón 2"},
	{"farming:cotton_3",				"Algodón 3"},
	{"farming:cotton_4",				"Algodón 4"},
	{"farming:cotton_5",				"Algodón 5"},
	{"farming:string",					""},
	{"farming:hoe_wood",				""},
	{"farming:hoe_stone",				""},
	{"farming:hoe_steel",				""},
	{"farming:hoe_bronze",				""},
	{"farming:hoe_mese",				""},
	{"farming:weed",					""},
	{"farming:seed_wheat",				""},
	{"farming:wheat",					"Trigo"},
	{"farming:wheat_1",					"Trigo 1"},
	{"farming:wheat_2",					"Trigo 2"},
	{"farming:wheat_3",					"Trigo 3"},
	{"farming:wheat_4",					"Trigo 4"},
	{"farming:wheat_5",					"Trigo 5"},
	{"farming:wheat_6",					"Trigo 6"},
	{"farming:wheat_7",					"Trigo 7"},
	{"farming:wheat_8",					"Trigo 8"},
	{"farming:flour",					"Harina"},
	{"farming:dough",					""},
	{"farming:bread",					"Pan"},
	
	-- fire
	{"fire:basic_flame",				"Llama básica"},
	
	-- flowers
	{"flowers:dandelion_white",			""},
	{"flowers:dandelion_yellow",			""},
	{"flowers:geranium",				"Geranio"},
	{"flowers:rose",					"Rosa"},
	{"flowers:tulip",					"Tulipán"},
	{"flowers:viola",					"Violeta"},
	
	-- nodetest
	{"nodetest:bone",					"Hueso"},
	{"nodetest:desert_sandstone",			""},
	{"nodetest:rock",					"Roca"},
	{"nodetest:tree_horizontal",			""},
	{"nodetest:jungletree_horizontal",		""},
	{"nodetest:papyrus_roots",			"Raíces de papiro"},
--	{"nodetest:conifersapling",			""},
--	{"nodetest:conifertree",				""},
--	{"nodetest:coniferleaves_1",			""},
--	{"nodetest:coniferleaves_2",			""},
--	{"nodetest:conifertree_horizontal",	""},
	{"nodetest:spearwood",				""},
	{"nodetest:spearstone",				""},
	
	-- pots
--	{"pots:pot",						""},
--	{"pots:cactus",					""},
--	{"pots:dandelion_white",				""},
--	{"pots:dandelion_yellow",			""},
--	{"pots:geranium",					""},
--	{"pots:rose",						""},
--	{"pots:tulip",						""},
--	{"pots:viola",						""},
	
	-- screwdriver
	{"screwdriver:screwdriver",			"Destornillador"},
--	{"screwdriver:screwdriver1",			""},
--	{"screwdriver:screwdriver2",			""},
--	{"screwdriver:screwdriver3",			""},
--	{"screwdriver:screwdriver4",			""},
	
	-- wool
	{"wool:white",						"Lana blanca"},
	{"wool:grey",						"Lana gris"},
	{"wool:dark_grey",					"Lana gris oscura"},
	{"wool:black",						"Lana negra"},
	{"wool:violet",					"Lana morada"},
	{"wool:blue",						"Lana azul"},
	{"wool:cyan",						"Lana azul celeste"},
	{"wool:dark_green",					"Lana verde oscura"},
	{"wool:green",						"Lana verde"},
	{"wool:yellow",					"Lana amarilla"},
	{"wool:brown",						"Lana marrón"},
	{"wool:orange",					"Lana naranja"},
	{"wool:red",						"Lana roja"},
	{"wool:magenta",					"Lana magenta"},
	{"wool:pink",						"Lana rosa"},

	-- vessels
	{"vessels:glass_bottle",				"Botella de cristal"},
	{"vessels:drinking_glass",			"Vaso para beber"},
	{"vessels:steel_bottle",				"Botella de acero"},
	{"vessels:glass_fragments",			"Trozos de cristal"},
}
