vortoj = {
	-- Boats
	{"boats:boat",					""},
	
	-- bones
	{"bones:bones",					"Ossements"},
	
	-- bucket
	{"bucket:bucket_empty",				"Seau"},
	{"bucket:bucket_water",				"Seau d'eau"},
	{"bucket:bucket_lava",				"Seau de lave"},
	
	-- default
	-- craftitems
	{"default:stick",					"Baton"},
	{"default:paper",					"Papier"},
	{"default:book",					"Livre"},
	{"default:coal_lump",				"Charbon"},
	{"default:iron_lump",				"Minerai de fer"},
	{"default:copper_lump",				"Minerai de cuivre"},
	{"default:mese_crystal",				"Cristal de Mese"},
	{"default:gold_lump",				""},
	{"default:diamond",					""},
	{"default:clay_lump",				"Argile"},
	{"default:steel_ingot",				"Lingot d'acier"},
	{"default:copper_ingot",				"Lingot de cuivre"},
	{"default:bronze_ingot",				""},
	{"default:gold_ingot",				""},
	{"default:mese_crystal_fragment",		"Eclat de Mese"},
	{"default:clay_brick",				"Brique d'argile"},
	{"default:scorched_stuff",			"Debris"},
	{"default:obsidian_shard",			""},
	-- nodes
	{"default:stone",					"Pierre"},
	{"default:desert_stone",				"Pierre du desert"},
	{"default:stone_with_coal",			"Veine de charbon"},
	{"default:stone_with_iron",			"Veine de fer"},
	{"default:stone_with_copper",			"Veine de cuivre"},
	{"default:stone_with_mese",			"Veine de Mese"},
	{"default:stone_with_gold",			""},
	{"default:stone_with_diamond",		""},
	{"default:stone_stonebrick",			""},
	{"default:stone_desert_stonebrick",	""},
	{"default:dirt_with_grass",			"Terre enherbee"},
	{"default:dirt_with_grass_footsteps",	"Terre enherbee pietinnee"},
	{"default:dirt_with_snow",			"Terre enneigee"},
	{"default:dirt",					"Terre"},
	{"default:sand",					"Sable"},
	{"default:desert_sand",				"Sable du desert"},
	{"default:gravel",					"Gravier"},
	{"default:sandstone",				"Gres"},
	{"default:sandstonebrick",			""},
	{"default:clay",					"Glaise"},
	{"default:brick",					"Briques"},
	{"default:tree",					"Arbre"},
	{"default:jungletree",				"Arbre exotique"},
	{"default:junglewood",				""},
	{"default:jungleleaves",				"Feuilles d'arbre exotique"},
	{"default:junglesapling",			"Pousse d'arbre exotique"},
	{"default:junglegrass",				"Herbe exotique"},
	{"default:leaves",					"Feuilles"},
	{"default:cactus",					"Cactus"},
	{"default:papyrus",					"Papyrus"},
	{"default:bookshelf",				"Etagere"},
	{"default:glass",					"Verre"},
	{"default:fence_wood",				"Cloture en bois"},
	{"default:rail",					"Rail"},
	{"default:ladder",					"Echelle"},
	{"default:wood",					"Bois"},
	{"default:cloud",					"Nuage"},
	{"default:water_flowing",			"Eau vive"},
	{"default:water_source",				"Source d'eau"},
	{"default:lava_flowing",				"Lave vive"},
	{"default:lava_source",				"Source de lave"},
	{"default:torch",					"Torche"},
	{"default:sign_wall",				"Panneau"},
	{"default:chest",					"Coffre"},
	{"default:chest_locked",				"Coffre verouille"},
	{"default:furnace",					"Four"},
	{"default:furnace_active",			"Four actif"},
	{"default:cobble",					"Cailloux"},
	{"default:mossycobble",				"Cailloux moussus"},
	{"default:coalblock",				"Bloc de charbon"},
	{"default:steelblock",				"Bloc d'acier"},
	{"default:copperblock",				"Bloc de cuivre"},
	{"default:bronzeblock",				""},
	{"default:mese",					"Mese"},
	{"default:goldblock",				""},
	{"default:diamondblock",				""},
	{"default:obsidian_glass",			""},
	{"default:obsidian",				""},
	{"default:nyancat",					"Nyan Cat"},
	{"default:nyancat_rainbow",			"Arc en Nyan"},
	{"default:sapling",					"Pousse d'arbre"},
	{"default:apple",					"Pomme"},
	{"default:dry_shrub",				"Arbuste desseche"},
	{"default:grass_1",					"Herbe"},
	{"default:grass_2",					"Herbe"},
	{"default:grass_3",					"Herbe"},
	{"default:grass_4",					"Herbe"},
	{"default:grass_5",					"Herbe"},
	{"default:ice",					"Glace"},
	{"default:snow",					"Neige"},
	{"default:snowblock",				"Bloc de neige"},
	-- tools
	{"default:pick_bronze",					""},
	{"default:pick_diamond",				""},
	{"default:pick_wood",				"Pioche en bois"},
	{"default:pick_stone",				"Pioche en pierre"},
	{"default:pick_copper",				"Pioche en cuivre"},
	{"default:pick_steel",				"Pioche en acier"},
	{"default:pick_mese",				"Pioche en Mese"},
	{"default:shovel_bronze",				""},
	{"default:shovel_diamond",				""},
	{"default:shovel_mese",					""},
	{"default:shovel_wood",				"Pelle en bois"},
	{"default:shovel_stone",				"Pelle en pierre"},
	{"default:shovel_copper",			"Pelle en cuivre"},
	{"default:shovel_steel",				"Pelle en acier"},
	{"default:axe_bronze",					""},
	{"default:axe_diamond",					""},
	{"default:axe_mese",					""},
	{"default:axe_wood",				"Hache en bois"},
	{"default:axe_stone",				"Hache en pierre"},
	{"default:axe_copper",				"Hache en cuivre"},
	{"default:axe_steel",				"Hache en acier"},
	{"default:sword_bronze",				""},
	{"default:sword_diamond",				""},
	{"default:sword_mese",					""},
	{"default:sword_wood",				"Epee en bois"},
	{"default:sword_stone",				"Epee en pierre"},
	{"default:sword_copper",				"Epee en cuivre"},
	{"default:sword_steel",				"Epee en acier"},
	
	-- doors
	{"doors:door_wood",					"Porte en bois"},
	{"doors:door_steel",				"Porte en acier"},
	{"doors:door_glass",					""},
	{"doors:door_obsidian_glass",				""},
	{"doors:trapdoor",					""},
	
	-- dye
	{"dye:white",						"Teinture blanche"},
	{"dye:grey",						"Teinture grise"},
	{"dye:dark_grey",					"Teinture anthracite"},
	{"dye:black",						"Teinture noire"},
	{"dye:violet",						"Teinture violette"},
	{"dye:blue",						"Teinture bleue"},
	{"dye:cyan",						"Teinture cyan"},
	{"dye:dark_green",					"Teinture emeraude"},
	{"dye:green",						"Teinture verte"},
	{"dye:yellow",						"Teinture jaune"},
	{"dye:brown",						"Teinture brune"},
	{"dye:orange",						"Teinture orange"},
	{"dye:red",						"Teinture rouge"},
	{"dye:magenta",					"Teinture magenta"},
	{"dye:pink",						"Teinture rose"},
	
	-- farming
	{"farming:soil",					""},
	{"farming:soil_wet",				""},
	{"farming:seed_cotton",				"Coton"},
	{"farming:cotton",					"Coton"},
	{"farming:sting",					"Aiguille"},
	{"farming:hoe_wood",				"Houe en bois"},
	{"farming:hoe_stone",				"Houe en pierre"},
	{"farming:hoe_steel",				"Houe en acier"},
	{"farming:hoe_bronze",				""},
	{"farming:hoe_mese",				"Houe en Mese"},
	{"farming:weed",					"Graine"},
	{"farming:seed_wheat",				""},
	{"farming:wheat",					"Ble"},
	{"farming:flour",					"Farine"},
	{"farming:dough",					"Paton"},
	{"farming:bread",					"Pain"},
	
	-- fire
	{"fire:basic_flame",				"Flamme"},
	
	-- flowers
	{"flowers:dandelion_white",			"Pissenlit blanc"},
	{"flowers:dandelion_yellow",			"Pissenlit jaune"},
	{"flowers:geranium",				"Geranium"},
	{"flowers:rose",					"Rose"},
	{"flowers:tulip",					"Tulipe"},
	{"flowers:viola",					"Violette"},
	
	-- screwdriver
	{"screwdriver:screwdriver",			"Tournevis"},
	{"screwdriver:screwdriver1",			"Tournevis"},
	{"screwdriver:screwdriver2",			"Tournevis"},
	{"screwdriver:screwdriver3",			"Tournevis"},
	{"screwdriver:screwdriver4",			"Tournevis"},
	
	-- Stairs
	--Slab
	{"stairs:slab_wood",					""},
	{"stairs:slab_stone",					""},
	{"stairs:slab_cobble",					""},
	{"stairs:slab_desert_stone",				""},
	{"stairs:slab_desert_cobble",				""},
	{"stairs:slab_desert_stonebrick",			""},
	{"stairs:slab_brick",					""},
	{"stairs:slab_sandstone",				""},
	{"stairs:slab_sandstonebrick",				""},
	{"stairs:slab_junglewood",				""},
	{"stairs:slab_stonebrick",				""},
	--Stair
	{"stairs:stair_wood",					""},
	{"stairs:stair_stone",					""},
	{"stairs:stair_cobble",					""},
	{"stairs:stair_desert_stone",				""},
	{"stairs:stair_desert_cobble",				""},
	{"stairs:stair_desert_stonebrick",			""},
	{"stairs:stair_brick",					""},
	{"stairs:stair_sandstone",				""},
	{"stairs:stair_sandstonebrick",				""},
	{"stairs:stair_junglewood",				""},
	{"stairs:stair_stonebrick",				""},
	
	-- TNT
	{"tnt:tnt",					"TNT"},
	{"tnt:gunpowder",					""},
	
	-- vessels
	{"vessels:glass_bottle",				""},
	{"vessels:drinking_glass",			""},
	{"vessels:steel_bottle",				""},
	{"vessels:glass_fragments",			""},
	
	-- wool
	{"wool:white",						"Laine blanche"},
	{"wool:grey",						"Laine grise"},
	{"wool:dark_grey",					"Laine anthracite"},
	{"wool:black",						"Laine noire"},
	{"wool:violet",					"Laine violette"},
	{"wool:blue",						"Laine bleue"},
	{"wool:cyan",						"Laine cyan"},
	{"wool:dark_green",					"Laine emeraude"},
	{"wool:green",						"Laine verte"},
	{"wool:yellow",					"Laine jaune"},
	{"wool:brown",						"Laine brune"},
	{"wool:orange",					"Laine orange"},
	{"wool:red",						"Laine rouge"},
	{"wool:magenta",					"Laine magenta"},
	{"wool:pink",						"Laine rose"},
	
	-- Xpanes
	{"xpanes:pane",					""},
	{"xpanes:bar",					""},
}
