return {
	-- bones
	{"bones:bones",					"Ossements"},
	
	-- bucket
	{"bucket:bucket_empty",				"Seau"},
	{"bucket:bucket_water",				"Seau d'eau"},
	{"bucket:bucket_lava",				"Seau de lave"},
	
	-- default
	-- craftitems
	{"default:stick",					"Bâton"},
	{"default:paper",					"Papier"},
	{"default:book",					"Livre"},
	{"default:coal_lump",				"Charbon"},
	{"default:iron_lump",				"Minerai de fer"},
	{"default:copper_lump",				"Minerai de cuivre"},
	{"default:mese_crystal",				"Cristal de Mese"},
	{"default:gold_lump",				""},
	{"default:diamond",					""},
	{"default:clay_lump",				"Argile"},
	{"default:steel_ingot",				"Lingot d'acier"},
	{"default:copper_ingot",				"Lingot de cuivre"},
	{"default:bronze_ingot",				""},
	{"default:gold_ingot",				""},
	{"default:mese_crystal_fragment",		"Éclat de Mese"},
	{"default:clay_brick",				"Brique d'argile"},
	{"default:scorched_stuff",			"Débris"},
	{"default:obsidian_shard",			""},
	-- nodes
	{"default:stone",					"Pierre"},
	{"default:desert_stone",				"Pierre du désert"},
	{"default:stone_with_coal",			"Veine de charbon"},
	{"default:stone_with_iron",			"Veine de fer"},
	{"default:stone_with_copper",			"Veine de cuivre"},
	{"default:stone_with_mese",			"Veine de Mese"},
	{"default:stone_with_gold",			""},
	{"default:stone_with_diamond",		""},
	{"default:stone_stonebrick",			""},
	{"default:stone_desert_stonebrick",	""},
	{"default:dirt_with_grass",			"Terre enherbée"},
	{"default:dirt_with_grass_footsteps",	"Terre enherbée piétinnée"},
	{"default:dirt_with_snow",			"Terre enneigée"},
	{"default:dirt",					"Terre"},
	{"default:sand",					"Sable"},
	{"default:desert_sand",				"Sable du désert"},
	{"default:gravel",					"Gravier"},
	{"default:sandstone",				"Grès"},
	{"default:sandstonebrick",			""},
	{"default:clay",					"Glaise"},
	{"default:brick",					"Briques"},
	{"default:tree",					"Arbre"},
	{"default:jungletree",				"Arbre exotique"},
	{"default:junglewood",				""},
	{"default:jungleleaves",				"Feuilles d'arbre exotique"},
	{"default:junglesapling",			"Pousse d'arbre exotique"},
	{"default:junglegrass",				"Herbe exotique"},
	{"default:leaves",					"Feuilles"},
	{"default:cactus",					"Cactus"},
	{"default:papyrus",					"Papyrus"},
	{"default:bookshelf",				"Étagère"},
	{"default:glass",					"Verre"},
	{"default:fence_wood",				"Clotûre en bois"},
	{"default:rail",					"Rail"},
	{"default:ladder",					"Échelle"},
	{"default:wood",					"Bois"},
	{"default:cloud",					"Nuage"},
	{"default:water_flowing",			"Eau vive"},
	{"default:water_source",				"Source d'eau"},
	{"default:lava_flowing",				"Lave vive"},
	{"default:lava_source",				"Source de lave"},
	{"default:torch",					"Torche"},
	{"default:sign_wall",				"Panneau"},
	{"default:chest",					"Coffre"},
	{"default:chest_locked",				"Coffre verouillé"},
	{"default:furnace",					"Four"},
	{"default:furnace_active",			"Four actif"},
	{"default:cobble",					"Cailloux"},
	{"default:mossycobble",				"Cailloux moussus"},
	{"default:coalblock",				"Bloc de charbon"},
	{"default:steelblock",				"Bloc d'acier"},
	{"default:copperblock",				"Bloc de cuivre"},
	{"default:bronzeblock",				""},
	{"default:mese",					"Mese"},
	{"default:goldblock",				""},
	{"default:diamondblock",				""},
	{"default:obsidian_glass",			""},
	{"default:obsidian",				""},
	{"default:nyancat",					"Nyan Cat"},
	{"default:nyancat_rainbow",			"Arc en Nyan"},
	{"default:sapling",					"Pousse d'arbre"},
	{"default:apple",					"Pomme"},
	{"default:dry_shrub",				"Arbuste desseché"},
	{"default:grass_1",					"Herbe"},
	{"default:grass_2",					"Herbe"},
	{"default:grass_3",					"Herbe"},
	{"default:grass_4",					"Herbe"},
	{"default:grass_5",					"Herbe"},
	{"default:ice",					"Glâce"},
	{"default:snow",					"Neige"},
	{"default:snowblock",				"Bloc de neige"},
	-- tools
	{"default:pick_wood",				"Pioche en bois"},
	{"default:pick_stone",				"Pioche en pierre"},
	{"default:pick_copper",				"Pioche en cuivre"},
	{"default:pick_steel",				"Pioche en acier"},
	{"default:pick_mese",				"Pioche en Mese"},
	{"default:shovel_wood",				"Pelle en bois"},
	{"default:shovel_stone",				"Pelle en pierre"},
	{"default:shovel_copper",			"Pelle en cuivre"},
	{"default:shovel_steel",				"Pelle en acier"},
	{"default:axe_wood",				"Hache en bois"},
	{"default:axe_stone",				"Hache en pierre"},
	{"default:axe_copper",				"Hache en cuivre"},
	{"default:axe_steel",				"Hache en acier"},
	{"default:sword_wood",				"Épée en bois"},
	{"default:sword_stone",				"Épée en pierre"},
	{"default:sword_copper",				"Épée en cuivre"},
	{"default:sword_steel",				"Épée en acier"},
	
	-- doors
	{"doors:door_wood",					"Porte en bois"},
	{"doors:door_steel",				"Porte en acier"},
	
	-- dye
	{"dye:white",						"Teinture blanche"},
	{"dye:grey",						"Teinture grise"},
	{"dye:dark_grey",					"Teinture anthracite"},
	{"dye:black",						"Teinture noire"},
	{"dye:violet",						"Teinture violette"},
	{"dye:blue",						"Teinture bleue"},
	{"dye:cyan",						"Teinture cyan"},
	{"dye:dark_green",					"Teinture émeraude"},
	{"dye:green",						"Teinture verte"},
	{"dye:yellow",						"Teinture jaune"},
	{"dye:brown",						"Teinture brune"},
	{"dye:orange",						"Teinture orange"},
	{"dye:red",						"Teinture rouge"},
	{"dye:magenta",					"Teinture magenta"},
	{"dye:pink",						"Teinture rose"},
	
	-- farming
	{"farming:soil",					""},
	{"farming:soil_wet",				""},
	{"farming:seed_cotton",				"Coton"},
	{"farming:cotton",					"Coton"},
	{"farming:cotton_1",				"Coton"},
	{"farming:cotton_2",				"Coton"},
	{"farming:cotton_3",				"Coton"},
	{"farming:cotton_4",				"Coton"},
	{"farming:cotton_5",				"Coton"},
	{"farming:sting",					"Aiguille"},
	{"farming:hoe_wood",				"Houe en bois"},
	{"farming:hoe_stone",				"Houe en pierre"},
	{"farming:hoe_steel",				"Houe en acier"},
	{"farming:hoe_bronze",				""},
	{"farming:hoe_mese",				"Houe en Mese"},
	{"farming:weed",					"Graine"},
	{"farming:seed_wheat",				""},
	{"farming:wheat",					"Blé"},
	{"farming:wheat_1",					"Blé"},
	{"farming:wheat_2",					"Blé"},
	{"farming:wheat_3",					"Blé"},
	{"farming:wheat_4",					"Blé"},
	{"farming:wheat_5",					"Blé"},
	{"farming:wheat_6",					"Blén"},
	{"farming:wheat_7",					"Blé"},
	{"farming:wheat_8",					"Blé"},
	{"farming:flour",					"Farine"},
	{"farming:dough",					"Pâton"},
	{"farming:bread",					"Pain"},
	
	-- fire
	{"fire:basic_flame",				"Flamme"},
	
	-- flowers
	{"flowers:dandelion_white",			"Pissenlit blanc"},
	{"flowers:dandelion_yellow",			"Pissenlit jaune"},
	{"flowers:geranium",				"Geranium"},
	{"flowers:rose",					"Rose"},
	{"flowers:tulip",					"Tulipe"},
	{"flowers:viola",					"Violette"},
	
	-- nodetest
	{"nodetest:bone",					"Ossement"},
	{"nodetest:desert_sandstone",			"Grès du désert"},
	{"nodetest:rock",					"Rocher"},
	{"nodetest:tree_horizontal",			"Arbre couché"},
	{"nodetest:jungletree_horizontal",		"Arbre exotique couché"},
	{"nodetest:papyrus_roots",			"Racines de papyrus"},
	{"nodetest:conifersapling",			"Pousse de sapin"},
	{"nodetest:conifertree",				"Sapin"},
	{"nodetest:coniferleaves_1",			"Aiguilles de sapin"},
	{"nodetest:coniferleaves_2",			"Aiguilles de sapin"},
	{"nodetest:conifertree_horizontal",	"Sapin couché"},
	{"nodetest:spearwood",				"Lance en bois"},
	{"nodetest:spearstone",				"Lance en pierre"},
	
	-- pots
	{"pots:pot",						"Pot"},
	{"pots:cactus",					"Cactus en pot"},
	{"pots:dandelion_white",				"Pissenlit blanc en pot"},
	{"pots:dandelion_yellow",			"Pissenlit jaune en pot"},
	{"pots:geranium",					"Geranium en pot"},
	{"pots:rose",						"Rose en pot"},
	{"pots:tulip",						"Tulipe en pot"},
	{"pots:viola",						"Violette en pot"},
	{"pots:viola",						"Violette en pot"},
	
	-- screwdriver
	{"screwdriver:screwdriver",			"Tournevis"},
	{"screwdriver:screwdriver1",			"Tournevis"},
	{"screwdriver:screwdriver2",			"Tournevis"},
	{"screwdriver:screwdriver3",			"Tournevis"},
	{"screwdriver:screwdriver4",			"Tournevis"},
	
	-- wool
	{"wool:white",						"Laine blanche"},
	{"wool:grey",						"Laine grise"},
	{"wool:dark_grey",					"Laine anthracite"},
	{"wool:black",						"Laine noire"},
	{"wool:violet",					"Laine violette"},
	{"wool:blue",						"Laine bleue"},
	{"wool:cyan",						"Laine cyan"},
	{"wool:dark_green",					"Laine émeraude"},
	{"wool:green",						"Laine verte"},
	{"wool:yellow",					"Laine jaune"},
	{"wool:brown",						"Laine brune"},
	{"wool:orange",					"Laine orange"},
	{"wool:red",						"Laine rouge"},
	{"wool:magenta",					"Laine magenta"},
	{"wool:pink",						"Laine rose"},

	-- vessels
	{"vessels:glass_bottle",				""},
	{"vessels:drinking_glass",			""},
	{"vessels:steel_bottle",				""},
	{"vessels:glass_fragments",			""},
}
