-- Licence for this file and translations: CC0

return {
	-- beds
	{"beds:bed",						"Tempat Tidur"},

	-- bones
	{"bones:bones",						"Tulang"},
	
	-- bucket
	{"bucket:bucket_empty",				"Ember Kosong"},
	{"bucket:bucket_water",				"Ember Air"},
	{"bucket:bucket_lava",				"Ember Lava"},

	-- carts
	{"carts:cart",						"Kereta"},
	{"carts:powerrail",					"Rel Tenaga"},
	{"carts:brakerail",					"Rel Rem"},
	
	-- default
	-- craftitems
	{"default:stick",					"Tongkat"},
	{"default:paper",					"Kertas"},
	{"default:book",					"Buku"},
	{"default:coal_lump",				"Bongkahan Batu Bara"},
	{"default:iron_lump",				"Bongkahan Besi"},
	{"default:copper_lump",				"Bongkahan Tembaga"},
	{"default:mese_crystal",			"Kristal Mese"},
	{"default:gold_lump",				"Bongkahan Emas"},
	{"default:diamond",					"Berlian"},
	{"default:clay_lump",				"Bongkahan Semen"},
	{"default:steel_ingot",				"Batangan Baja"},
	{"default:copper_ingot",			"Batangan Tembaga"},
	{"default:bronze_ingot",			"Batangan Perunggu"},
	{"default:gold_ingot",				"Batangan Emas"},
	{"default:mese_crystal_fragment",	"Pecahan Kristal Mese"},
	{"default:clay_brick",				"Tembok Semen"},
	{"default:scorched_stuff",			"Benda Hangus"},
	{"default:obsidian_shard",			"Pecahan Obsidian"},
	-- nodes
	{"default:stone",						"Batu"},
	{"default:desert_stone",				"Batu Gurun"},
	{"default:stone_with_coal",				"Batu dengan Batu Bara"},
	{"default:stone_with_iron",				"Batu dengan Besi"},
	{"default:stone_with_copper",			"Batu dengan Tembaga"},
	{"default:stone_with_mese",				"Batu dengan Mese"},
	{"default:stone_with_gold",				"Batu dengan Emas"},
	{"default:stone_with_diamond",			"Batu dengan Berlian"},
	{"default:stone_stonebrick",			"Tembok Batu"},
	{"default:stone_desert_stonebrick",		"Tembok Batu Gurun"},
	{"default:dirt_with_grass",				"Tanah dengan Rumput"},
	{"default:dirt_with_grass_footsteps",	"Tanah dengan Rumput dan Jejak Kaki"},
	{"default:dirt_with_snow",				"Tanah dengan Salju"},
	{"default:dirt",						"Tanah"},
	{"default:sand",						"Pasir"},
	{"default:desert_sand",					"Pasir Gurun"},
	{"default:gravel",						"Kerikil"},
	{"default:sandstone",					"Batu Pasir"},
	{"default:sandstonebrick",				"Tembok Batu Pasir"},
	{"default:clay",						"Semen"},
	{"default:brick",						"Bata"},
	{"default:tree",						"Pohon"},
	{"default:jungletree",					"Pohon Rimba"},
	{"default:junglewood",					"Kayu Pohon Rimba"},
	{"default:jungleleaves",				"Daun Pohon Rimba"},
	{"default:junglesapling",				"Anak Pohon Rimba"},
	{"default:junglegrass",					"Rumput Rimba"},
	{"default:leaves",						"Daun"},
	{"default:cactus",						"Kaktus"},
	{"default:papyrus",						"Papirus"},
	{"default:bookshelf",					"Lemari Buku"},
	{"default:glass",						"Kaca"},
	{"default:fence_wood",					"Pagar Kayu"},
	{"default:rail",						"Rel"},
	{"default:ladder",						"Tangga"},
	{"default:wood",						"Kayu"},
	{"default:cloud",						"Awan"},
	{"default:water_flowing",				"Air Mengalir"},
	{"default:water_source",				"Sumber Air"},
	{"default:lava_flowing",				"Lava Mengalir"},
	{"default:lava_source",					"Sumber Lava"},
	{"default:torch",						"Obor"},
	{"default:sign_wall",					"Papan Tembok"},
	{"default:chest",						"Peti"},
	{"default:chest_locked",				"Peti Terkunci"},
	{"default:furnace",						"Perapian"},
	{"default:furnace_active",				"Perapian"},
	{"default:cobble",						"Batu Alam"},
	{"default:mossycobble",					"Batu Alam Berlumut"},
	{"default:coalblock",					"Balok Batu Bara"},
	{"default:steelblock",					"Balok Baja"},
	{"default:copperblock",					"Balok Tembaga"},
	{"default:bronzeblock",					"Balok Perunggu"},
	{"default:mese",						"Mese"},
	{"default:goldblock",					"Balok Emas"},
	{"default:diamondblock",				"Balok Berlian"},
	{"default:obsidian_glass",				"Kaca Obsidian"},
	{"default:obsidian",					"Obsidian"},
	{"default:nyancat",						"Nyan Cat"},
	{"default:nyancat_rainbow",				"Nyan Cat Rainbow"},
	{"default:sapling",						"Anak Pohon"},
	{"default:apple",						"Apel"},
	{"default:dry_shrub",					"Semak Belukar Kering"},
	{"default:grass_1",						"Rumput"},
	{"default:grass_2",						"Rumput"},
	{"default:grass_3",						"Rumput"},
	{"default:grass_4",						"Rumput"},
	{"default:grass_5",						"Rumput"},
	{"default:ice",							"Balok Es"},
	{"default:snow",						"Salju"},
	{"default:snowblock",					"Balok Salju"},
	-- tools
	{"default:pick_wood",				"Beliung Kayu"},
	{"default:pick_stone",				"Beliung Batu"},
	{"default:pick_copper",				"Beliung Tembaga"},
	{"default:pick_steel",				"Beliung Baja"},
	{"default:pick_mese",				"Beliung Mese"},
	{"default:shovel_wood",				"Sekop Kayu"},
	{"default:shovel_stone",			"Sekop Batu"},
	{"default:shovel_copper",			"Sekop Tembaga"},
	{"default:shovel_steel",			"Sekop Baja"},
	{"default:axe_wood",				"Kapak Kayu"},
	{"default:axe_stone",				"Kapak Batu"},
	{"default:axe_copper",				"Kapak Tembaga"},
	{"default:axe_steel",				"Kapak Baja"},
	{"default:sword_wood",				"Pedang Kayu"},
	{"default:sword_stone",				"Pedang Batu"},
	{"default:sword_copper",			"Pedang Tembaga"},
	{"default:sword_steel",				"Pedang Baja"},
	
	-- doors
	{"doors:door_wood",					"Pintu Kayu"},
	{"doors:door_steel",				"Pintu Baja"},
	
	-- dye
	{"dye:white",						"Pewarna Putih"},
	{"dye:grey",						"Pewarna Abu-Abu"},
	{"dye:dark_grey",					"Pewarna Abu-Abu Gelap"},
	{"dye:black",						"Pewarna Hitam"},
	{"dye:violet",						"Pewarna Lembayung"},
	{"dye:blue",						"Pewarna Biru"},
	{"dye:cyan",						"Pewarna Biru Kehijauan"},
	{"dye:dark_green",					"Pewarna Hijau Gelap"},
	{"dye:green",						"Pewarna Hijau"},
	{"dye:yellow",						"Pewarna Kuning"},
	{"dye:brown",						"Pewarna Coklat"},
	{"dye:orange",						"Pewarna Jingga"},
	{"dye:red",							"Pewarna Merah"},
	{"dye:magenta",						"Pewarna Merah Keunguan"},
	{"dye:pink",						"Pewarna Merah Muda"},
	
	-- farming
	{"farming:soil",					"Tanah Subur"},
	{"farming:soil_wet",				"Tanah Subur Basah"},
	{"farming:seed_cotton",				"Benih Kapas"},
	{"farming:cotton",					"Kapas"},
	{"farming:cotton_1",				"Kapas"},
	{"farming:cotton_2",				"Kapas"},
	{"farming:cotton_3",				"Kapas"},
	{"farming:cotton_4",				"Kapas"},
	{"farming:cotton_5",				"Kapas"},
	{"farming:string",					"Benang"},
	{"farming:hoe_wood",				"Cangkul Kayu"},
	{"farming:hoe_stone",				"Cangkul Batu"},
	{"farming:hoe_steel",				"Cangkul Baja"},
	{"farming:hoe_bronze",				"Cangkul Perunggu"},
	{"farming:hoe_mese",				"Cangkul Mese"},
	{"farming:weed",					"Rumput Liar"},
	{"farming:seed_wheat",				"Benih Gandum"},
	{"farming:wheat",					"Gandum"},
	{"farming:wheat_1",					"Gandum"},
	{"farming:wheat_2",					"Gandum"},
	{"farming:wheat_3",					"Gandum"},
	{"farming:wheat_4",					"Gandum"},
	{"farming:wheat_5",					"Gandum"},
	{"farming:wheat_6",					"Gandum"},
	{"farming:wheat_7",					"Gandum"},
	{"farming:wheat_8",					"Gandum"},
	{"farming:flour",					"Tepung"},
	{"farming:dough",					"Adonan"},
	{"farming:bread",					"Roti"},
	
	-- fire
	{"fire:basic_flame",				"Api"},
	
	-- flowers
	{"flowers:dandelion_white",			"Bunga Dandelion Putih"},
	{"flowers:dandelion_yellow",		"Bunga Dandelion Kuning"},
	{"flowers:geranium",				"Bunga Geranium"},
	{"flowers:rose",					"Bunga Mawar"},
	{"flowers:tulip",					"Bunga Tulip"},
	{"flowers:viola",					"Bunga Viola"},
	
	-- nodetest
	{"nodetest:bone",					"Tulang"},
	{"nodetest:desert_sandstone",		"Batu Pasir Gurun"},
	{"nodetest:rock",					"Batu"},
	{"nodetest:tree_horizontal",		"Pohon Horizontal"},
	{"nodetest:jungletree_horizontal",	"Pohon Rimba Horizontal"},
	{"nodetest:papyrus_roots",			"Akar Papirus"},
--	{"nodetest:conifersapling",			""},
--	{"nodetest:conifertree",			""},
--	{"nodetest:coniferleaves_1",		""},
--	{"nodetest:coniferleaves_2",		""},
--	{"nodetest:conifertree_horizontal",	""},
	{"nodetest:spearwood",				"Tombak Kayu"},
	{"nodetest:spearstone",				"Tombak Batu"},
	
	-- pots
--	{"pots:pot",						""},
--	{"pots:cactus",						""},
--	{"pots:dandelion_white",			""},
--	{"pots:dandelion_yellow",			""},
--	{"pots:geranium",					""},
--	{"pots:rose",						""},
--	{"pots:tulip",						""},
--	{"pots:viola",						""},
	
	-- screwdriver
	{"screwdriver:screwdriver",			"Obeng"},
--	{"screwdriver:screwdriver1",		""},
--	{"screwdriver:screwdriver2",		""},
--	{"screwdriver:screwdriver3",		""},
--	{"screwdriver:screwdriver4",		""},
	
	-- wool
	{"wool:white",						"Wol Putih"},
	{"wool:grey",						"Wol Abu-Abu"},
	{"wool:dark_grey",					"Wol Abu-Abu Gelap"},
	{"wool:black",						"Wol Hitam"},
	{"wool:violet",						"Wol Lembayung"},
	{"wool:blue",						"Wol Biru"},
	{"wool:cyan",						"Wol Biru Kehijauan"},
	{"wool:dark_green",					"Wol Hijau"},
	{"wool:green",						"Wol Hijau Gelap"},
	{"wool:yellow",						"Wol Kuning"},
	{"wool:brown",						"Wol Coklat"},
	{"wool:orange",						"Wol Jingga"},
	{"wool:red",						"Wol Merah"},
	{"wool:magenta",					"Wol Merah Keunguan"},
	{"wool:pink",						"Wol Merah Muda"},

	-- vessels
	{"vessels:glass_bottle",			"Botol Kaca"},
	{"vessels:drinking_glass",			"Gelas Minum"},
	{"vessels:steel_bottle",			"Botol Baja"},
	{"vessels:glass_fragments",			"Pecahan Kaca"},
}
