return {
	-- bones
	{"bones:bones",				            	  "ossa"},
	
	-- bucket
	{"bucket:bucket_empty",			      	  "secchio vuoto"},
	{"bucket:bucket_water",		      		  "secchio con acqua"},
	{"bucket:bucket_lava",				        "secchio con lava"},
	
	-- default
	-- craftitems
	{"default:stick",		          			  "bastone"},
	{"default:paper",	          				  "carta"},
	{"default:book",			          		  "libro"},
	{"default:coal_lump",		        		  "pezzo di carbone"},
	{"default:iron_lump",		        		  "pezzo di ferro"},
	{"default:copper_lump",		      		  "pezzo di rame"},
	{"default:mese_crystal",    				  "cristallo di mese"},
	{"default:gold_lump",			        	  "pezzo di oro"},
	{"default:diamond",			        	  	"diamante"},
	{"default:clay_lump",	        	  		"pezzo di argilla"},
	{"default:steel_ingot",     	  			"lingotto di acciaio"},
	{"default:copper_ingot",		  	    	"lingotto di rame"},
	{"default:bronze_ingot",	      			"lingotto di bronzo"},
	{"default:gold_ingot",			        	"lingotto di oro"},
	{"default:mese_crystal_fragment", 		"frammento di cristallo di mese"},
	{"default:clay_brick",			        	"mattone di argilla"},
	{"default:scorched_stuff",		      	"roba bruciata"},
	{"default:obsidian_shard",		      	"scheggia di ossidiana"},
	-- nodes
	{"default:stone",				            	"pietra"},
	{"default:desert_stone",				      "pietra del deserto"},
	{"default:stone_with_coal",			      "pietra con carbone"},
	{"default:stone_with_iron",			      "pietra con ferro"},
	{"default:stone_with_copper",			    "pietra con rame"},
	{"default:stone_with_mese",			      "pietra con mese"},
	{"default:stone_with_gold",			      "pietra con oro"},
	{"default:stone_with_diamond",		    "pietra con diamante"},
	{"default:stone_stonebrick",			    "mattone di pietra"},
	{"default:stone_desert_stonebrick",	  "mattone di pietra del deserto"},
	{"default:dirt_with_grass",			      "terra con erba"},
	{"default:dirt_with_grass_footsteps",	"terra con orme sull'erba"},
	{"default:dirt_with_snow",			      "terra con neve"},
	{"default:dirt",					            "terra"},
	{"default:sand",					            "sabbia"},
	{"default:desert_sand",			        	"sabbia del deserto"},
	{"default:gravel",					          "ghiaia"},
	{"default:sandstone",			          	"arenaria"},
	{"default:sandstonebrick",			      "mattone di arenaria"},
	{"default:clay",					            "argilla"},
	{"default:brick",					            "mattone"},
	{"default:tree",					            "albero"},
	{"default:jungletree",				        "albero della giungla"},
	{"default:junglewood",				        "legno della giungla"},
	{"default:jungleleaves",				      "foglie della giungla"},
	{"default:junglesapling",			        "alberello della giungla"},
	{"default:junglegrass",				        "erba della giungla"},
	{"default:leaves",					          "foglie"},
	{"default:cactus",					          "cactus"},
	{"default:papyrus",					          "papiro"},
	{"default:bookshelf",				          "libreria"},
	{"default:glass",					            "vetro"},
	{"default:fence_wood",				        "recinto"},
	{"default:rail",					            "rotaia"},
	{"default:ladder",					          "scala a pioli"},
	{"default:wood",					            "legno"},
	{"default:cloud",					            "nuvola"},
	{"default:water_flowing",			        "acqua corrente"},
	{"default:water_source",				      "sorgente di acqua"},
	{"default:lava_flowing",				      "lava corrente"},
	{"default:lava_source",				        "sorgente di lava"},
	{"default:torch",					            "torcia"},
	{"default:sign_wall",				          "cartello"},
	{"default:chest",					            "cassa"},
	{"default:chest_locked",				      "cassa chiusa a chiave"},
	{"default:furnace",					          "fornace"},
	{"default:furnace_active",			      "fornace attiva"},
	{"default:cobble",					          "ciottoli"},
	{"default:mossycobble",				        "ciottoli muschiosi"},
	{"default:coalblock",				          "blocco di carbone"},
	{"default:steelblock",				        "blocco di acciaio"},
	{"default:copperblock",				        "blocco di rame"},
	{"default:bronzeblock",				        "blocco di bronzo"},
	{"default:mese",					            "mese"},
	{"default:goldblock",				          "blocco di oro"},
	{"default:diamondblock",				      "blocco di diamante"},
	{"default:obsidian_glass",			      "vetro di ossidiana"},
	{"default:obsidian",				          "ossidiana"},
	{"default:nyancat",					          "gatto nyan"},
	{"default:nyancat_rainbow",			      "arcobaleno del gatto nyan"},
	{"default:sapling",					          "alberello"},
	{"default:apple",					            "mela"},
	{"default:dry_shrub",				          "cespuglio secco"},
	{"default:grass_1",					          "erba 1"},
	{"default:grass_2",					          "erba 2"},
	{"default:grass_3",					          "erba 3"},
	{"default:grass_4",					          "erba 4"},
	{"default:grass_5",					          "erba 5"},
	{"default:ice",					              "ghiaccio"},
	{"default:snow",					            "neve"},
	{"default:snowblock",				          "blocco di neve"},
	-- tools
	{"default:pick_wood",			          	"piccone di legno"},
	{"default:pick_stone",	        			"piccone di pietra"},
	{"default:pick_copper",			        	"piccone di rame"},
	{"default:pick_steel",			        	"piccone di acciaio"},
	{"default:pick_mese",			          	"piccone di mese"},
	{"default:shovel_wood",			        	"pala di legno"},
	{"default:shovel_stone",			      	"pala di pietra"},
	{"default:shovel_copper",		        	"pala di rame"},
	{"default:shovel_steel",	      			"pala di acciaio"},
	{"default:axe_wood",			          	"ascia di legno"},
	{"default:axe_stone",				          "ascia di pietra"},
	{"default:axe_copper",				        "ascia di rame"},
	{"default:axe_steel",				          "ascia di acciaio"},
	{"default:sword_wood",				        "spada di legno"},
	{"default:sword_stone",				        "spada di pietra"},
	{"default:sword_copper",				      "spada di rame"},
	{"default:sword_steel",				        "spada di acciaio"},
	
	-- doors
	{"doors:door_wood",					          "porta di legno"},
	{"doors:door_steel",				          "porta di acciaio"},
	
	-- dye
	{"dye:white",						              "tintura bianca"},
	{"dye:grey",						              "tintura grigia"},
	{"dye:dark_grey",					            "tintura grigia scura"},
	{"dye:black",						              "tintura nera"},
	{"dye:violet",						            "tintura viola"},
	{"dye:blue",						              "tintura blu"},
	{"dye:cyan",						              "tintura turchese"},
	{"dye:dark_green",					          "tintura verde scuro"},
	{"dye:green",						              "tintura verde"},
	{"dye:yellow",						            "tintura gialla"},
	{"dye:brown",						              "tintura marrone"},
	{"dye:orange",						            "tintura arancione"},
	{"dye:red",						                "tintura rossa"},
	{"dye:magenta",					              "tintura magenta"},
	{"dye:pink",						              "tintura rosa"},
	
	-- farming
	{"farming:soil",					            "terra"},
	{"farming:soil_wet",				          "terra bagnata"},
	{"farming:seed_cotton",				        "seme di cotone"},
	{"farming:cotton",					          "cotone"},
	{"farming:cotton_1",				          "cotone 1"},
	{"farming:cotton_2",				          "cotone 2"},
	{"farming:cotton_3",				          "cotone 3"},
	{"farming:cotton_4",				          "cotone 4"},
	{"farming:cotton_5",				          "cotone 5"},
	{"farming:string",					          "filo"},
	{"farming:hoe_wood",				          "zappa di legno"},
	{"farming:hoe_stone",				          "zappa di pietra"},
	{"farming:hoe_steel",				          "zappa di acciaio"},
	{"farming:hoe_bronze",				        "zappa di bronzo"},
	{"farming:hoe_mese",				          "zappa di mese"},
	{"farming:weed",					            "erbaccia"},
	{"farming:seed_wheat",				        "seme di grano"},
	{"farming:wheat",					            "grano"},
	{"farming:wheat_1",					          "grano 1"},
	{"farming:wheat_2",					          "grano 2"},
	{"farming:wheat_3",					          "grano 3"},
	{"farming:wheat_4",					          "grano 4"},
	{"farming:wheat_5",					          "grano 5"},
	{"farming:wheat_6",					          "grano 6"},
	{"farming:wheat_7",					          "grano 7"},
	{"farming:wheat_8",					          "grano 8"},
	{"farming:flour",					            "farina"},
	{"farming:dough",					            "impasto"},
	{"farming:bread",					            "pane"},
	
	-- fire
	{"fire:basic_flame",				          "fiamma base"},
	
	-- flowers
	{"flowers:dandelion_white",			      "dente di leone bianco"},
	{"flowers:dandelion_yellow",		    	"dente di leone giallo"},
	{"flowers:geranium",			          	"geranio"},
	{"flowers:rose",					            "rosa"},
	{"flowers:tulip",					            "tulipano"},
	{"flowers:viola",					            "viola"},
	
	-- nodetest
	{"nodetest:bone",					            "osso"},
	{"nodetest:desert_sandstone",			    "arenaria del deserto"},
	{"nodetest:rock",					            "roccia"},
	{"nodetest:tree_horizontal",			    "albero orizzontale"},
	{"nodetest:jungletree_horizontal",		"albero della giungla orizzontale"},
	{"nodetest:papyrus_roots",			      "radici di papiro"},
	{"nodetest:conifersapling",			      "alberello di conifera"},
	{"nodetest:conifertree",				      "albero di conifera"},
	{"nodetest:coniferleaves_1",			    "foglie di conifera 1"},
	{"nodetest:coniferleaves_2",			    "foglie di conifera 2"},
	{"nodetest:conifertree_horizontal",	  "albero di conifera orizzontale"},
	{"nodetest:spearwood",				        "lancia di legno"},
	{"nodetest:spearstone",				        "lancia di pietra"},
	
	-- pots
	{"pots:pot",						              "vaso"},
	{"pots:cactus",					              "cactus"},
	{"pots:dandelion_white",				      "dente di leone bianco"},
	{"pots:dandelion_yellow",			        "dente di leone giallo"},
	{"pots:geranium",					            "geranio"},
	{"pots:rose",						              "rosa"},
	{"pots:tulip",						            "tulipano"},
	{"pots:viola",						            "viola"},
	{"pots:viola",						            "viola"},
	
	-- screwdriver
	{"screwdriver:screwdriver",			      "cacciavite"},
	{"screwdriver:screwdriver1",			    "cacciavite 1"},
	{"screwdriver:screwdriver2",			    "cacciavite 2"},
	{"screwdriver:screwdriver3",			    "cacciavite 3"},
	{"screwdriver:screwdriver4",			    "cacciavite 4"},
	
	-- wool
	{"wool:white",						            "lana bianca"},
	{"wool:grey",						              "lana grigia"},
	{"wool:dark_grey",					          "lana grigia scura"},
	{"wool:black",						            "lana nera"},
	{"wool:violet",					              "lana viola"},
	{"wool:blue",						              "lana blu"},
	{"wool:cyan",						              "lana turchese"},
	{"wool:dark_green",					          "lana verde scura"},
	{"wool:green",						            "lana verde"},
	{"wool:yellow",					              "lana gialla"},
	{"wool:brown",						            "lana marrone"},
	{"wool:orange",					              "lana arancione"},
	{"wool:red",						              "lana rossa"},
	{"wool:magenta",					            "lana magenta"},
	{"wool:pink",						              "lana rosa"},

	-- vessels
	{"vessels:glass_bottle",				      "bottiglia di vetro"},
	{"vessels:drinking_glass",			      "bicchiere"},
	{"vessels:steel_bottle",				      "bottiglia di acciaio"},
	{"vessels:glass_fragments",			      "cocci di vetro"},
}
