vortoj = {
	-- Boats
	{"boats:boat","ボート"},

	-- Bones
	{"bones:bones","骨"},

	-- Bucket
	{"bucket:bucket_empty","バケツ"},
	{"bucket:bucket_water","水入りバケツ"},
	{"bucket:bucket_lava","溶岩入りバケツ"},

	-- Default
	{"default:apple","リンゴ"},
	{"default:axe_bronze","青銅の斧"},
	{"default:axe_diamond","ダイヤモンドの斧"},
	{"default:axe_mese","MESEの斧"},
	{"default:axe_steel","鉄の斧"},
	{"default:axe_stone","石の斧"},
	{"default:axe_wood","木の斧"},
	{"default:book","本"},
	{"default:bookshelf","本棚"},
	{"default:brick","レンガブロック"},
	{"default:bronze_ingot","青銅インゴット"},
	{"default:bronzeblock","青銅ブロック"},
	{"default:cactus","サボテン"},
	{"default:chest","チェスト"},
	{"default:chest_locked","鍵のかかったチェスト"},
	{"default:clay","粘土ブロック"},
	{"default:clay_brick","棒レンガ"},
	{"default:clay_lump","粘土"},
	{"default:coal_lump","石炭"},
	{"default:coalblock","石炭ブロック"},
	{"default:cobble","丸石"},
	{"default:copper_ingot","銅インゴット"},
	{"default:copper_lump","銅"},
	{"default:copperblock","銅ブロック"},
	{"default:desert_cobble","砂漠の丸石"},
	{"default:desert_sand","砂漠の砂"},
	{"default:desert_stone","砂漠の砂石"},
	{"default:desert_stonebrick","赤レンガ"},
	{"default:diamond","ダイヤモンド"},
	{"default:diamondblock","ダイアモンドブロック"},
	{"default:dirt","土"},
	{"default:dirt_with_grass","草ブロック"},
	{"default:dirt_with_snow","雪付き草ブロック"},
	{"default:dry_shrub","枯れ木"},
	{"default:fence_wood","木のフェンス"},
	{"default:furnace","かまど"},
	{"default:glass","ガラス"},
	{"default:gold_ingot","金インゴット"},
	{"default:gold_lump","金"},
	{"default:goldblock","金ブロック"},
	{"default:grass_1","草"},
	{"default:gravel","砂利"},
	{"default:ice","氷"},
	{"default:iron_lump","鉄"},
	{"default:junglegrass","ジャングルの草"},
	{"default:jungleleaves","ジャングルの葉"},
	{"default:junglesapling","ジャングルの木の苗木"},
	{"default:jungletree","ジャングルの原木"},
	{"default:junglewood","ジャングルの木材"},
	{"default:ladder","はしご"},
	{"default:lava_source","溶岩"},
	{"default:leaves","葉"},
	{"default:mese","MESE"},
	{"default:mese_crystal","MESEクリスタル"},
	{"default:mese_crystal_fragment","MESEクリスタルの欠片"},
	{"default:mossycobble","苔石"},
	{"default:nyancat","NyanCat"},
	{"default:nyancat_rainbow","NyanCatの虹"},
	{"default:obsidian","黒曜石"},
	{"default:obsidian_glass","黒曜石ガラス"},
	{"default:obsidian_shard","黒曜石の破片"},
	{"default:obsidianbrick","黒曜石レンガ"},
	{"default:paper","紙"},
	{"default:papyrus","パピルス"},
	{"default:pick_bronze","青銅のピッケル"},
	{"default:pick_diamond","ダイヤモンドのピッケル"},
	{"default:pick_mese","MESEのピッケル"},
	{"default:pick_steel","鉄のピッケル"},
	{"default:pick_stone","石のピッケル"},
	{"default:pick_wood","木のピッケル"},
	{"default:pine_needles","マツの葉"},
	{"default:pine_sapling","マツの木の苗木"},
	{"default:pinetree","マツの原木"},
	{"default:pinewood","マツの木材"},
	{"default:rail","レール"},
	{"default:sand","砂"},
	{"default:sandstone","砂石"},
	{"default:sandstonebrick","砂レンガ"},
	{"default:sapling","苗木"},
	{"default:shovel_bronze","青銅のシャベル"},
	{"default:shovel_diamond","ダイヤモンドのシャベル"},
	{"default:shovel_mese","MESEのシャベル"},
	{"default:shovel_steel","鉄のシャベル"},
	{"default:shovel_stone","石のシャベル"},
	{"default:shovel_wood","木のシャベル"},
	{"default:sign_wall","看板"},
	{"default:snow","雪"},
	{"default:snowblock","雪ブロック"},
	{"default:steel_ingot","鉄インゴット"},
	{"default:steelblock","鉄ブロック"},
	{"default:stick","棒"},
	{"default:stone","石"},
	{"default:stone_with_coal","石炭鉱石"},
	{"default:stone_with_copper","銅鉱石"},
	{"default:stone_with_diamond","ダイヤモンド鉱石"},
	{"default:stone_with_gold","金鉱石"},
	{"default:stone_with_iron","鉄鉱石"},
	{"default:stone_with_mese","MESE鉱石"},
	{"default:stonebrick","石レンガ"},
	{"default:sword_bronze","青銅の剣"},
	{"default:sword_diamond","ダイヤモンドの剣"},
	{"default:sword_mese","MESEの剣"},
	{"default:sword_steel","鉄の剣"},
	{"default:sword_stone","石の剣"},
	{"default:sword_wood","木の剣"},
	{"default:torch","松明"},
	{"default:tree","原木"},
	{"default:water_source","水"},
	{"default:wood","木材"},

	-- Doors
	{"doors:door_glass","ガラスのドア"},
	{"doors:door_obsidian_glass","黒曜石ガラスのドア"},
	{"doors:door_steel","鉄のドア"},
	{"doors:door_wood","木のドア"},
	{"doors:trapdoor","トラップドア"},

	-- Dye
	{"dye:black","黒色の染料"},
	{"dye:blue","青色の染料"},
	{"dye:brown","茶色の染料"},
	{"dye:cyan","水色の染料"},
	{"dye:dark_green","緑色の染料"},
	{"dye:dark_grey","灰色の染料"},
	{"dye:green","黄緑色の染料"},
	{"dye:grey","薄灰色の染料"},
	{"dye:magenta","赤紫色の染料"},
	{"dye:orange","橙色の染料"},
	{"dye:pink","桃色の染料"},
	{"dye:red","赤色の染料"},
	{"dye:violet","紫色の染料"},
	{"dye:white","白色の染料"},
	{"dye:yellow","黄色の染料"},

	-- Farming
	{"farming:bread","パン"},
	{"farming:string","糸"},
	{"farming:flour","小麦粉"},
	{"farming:hoe_bronze","銅のクワ"},
	{"farming:hoe_diamond","ダイヤモンドのクワ"},
	{"farming:hoe_mese","MESEのクワ"},
	{"farming:hoe_steel","鉄のクワ"},
	{"farming:hoe_stone","石のクワ"},
	{"farming:hoe_wood","木のクワ"},
	{"farming:seed_cotton","コットンの種"},
	{"farming:seed_wheat","小麦の種"},
	{"farming:straw","干草の俵"},
	{"farming:wheat","小麦"},

	-- Fire
	{"fire:basic_flame","炎"},

	-- Flowers
	{"flowers:dandelion_white","白いタンポポ"},
	{"flowers:dandelion_yellow","タンポポ"},
	{"flowers:geranium","ゼラニウム"},
	{"flowers:rose","バラ"},
	{"flowers:tulip","チューリップ"},
	{"flowers:viola","ビオラ"},

	-- ScrewDriver
	{"screwdriver:screwdriver","スクリュードライバー"},
	{"screwdriver:screwdriver1","スクリュードライバー"},
	{"screwdriver:screwdriver2","スクリュードライバー"},
	{"screwdriver:screwdriver3","スクリュードライバー"},
	{"screwdriver:screwdriver4","スクリュードライバー"},

	-- Stairs
	-- Slabs
	{"stairs:slab_brick","レンガのハーフブロック"},
	{"stairs:slab_cobble","丸石のハーフブロック"},
	{"stairs:slab_desert_cobble","砂漠の丸石のハーフブロック"},
	{"stairs:slab_desert_stone","砂漠の砂石のハーフブロック"},
	{"stairs:slab_desert_stonebrick","赤レンガのハーフブロック"},
	{"stairs:slab_junglewood","ジャングルの木のハーフブロック"},
	{"stairs:slab_pinewood","マツの木のハーフブロック"},
	{"stairs:slab_obsidian","黒曜石のハーフブロック"},
	{"stairs:slab_obsidianbrick","黒曜石レンガのハーフブロック"},
	{"stairs:slab_sandstone","砂石のハーフブロック"},
	{"stairs:slab_sandstonebrick","砂レンガのハーフブロック"},
	{"stairs:slab_stone","石のハーフブロック"},
	{"stairs:slab_stonebrick","石レンガのハーフブロック"},
	{"stairs:slab_wood","木のハーフブロック"},
	-- Stairs
	{"stairs:stair_brick","レンガの階段"},
	{"stairs:stair_cobble","丸石の階段"},
	{"stairs:stair_desert_stone","砂漠の砂石の階段"},
	{"stairs:stair_desert_cobble","砂漠の丸石の階段"},
	{"stairs:stair_desert_stonebrick","赤レンガの階段"},
	{"stairs:stair_junglewood","ジャングルの木材の階段"},
	{"stairs:stair_obsidian","黒曜石の階段"},
	{"stairs:stair_obsidianbrick","黒曜石レンガの階段"},
	{"stairs:stair_pinewood","マツの木の階段"},
	{"stairs:stair_sandstone","砂石の階段"},
	{"stairs:stair_sandstonebrick","砂レンガの階段"},
	{"stairs:stair_stone","石の階段"},
	{"stairs:stair_stonebrick","石レンガの階段"},
	{"stairs:stair_wood","木の階段"},

	-- TNT
	{"tnt:gunpowder","火薬"},
	{"tnt:tnt","TNT"},

	-- Vessels
	{"vessels:drinking_glass","ドリンクボトル"},
	{"vessels:glass_bottle","ガラスのボトル"},
	{"vessels:glass_fragments","ガラスの欠片"},
	{"vessels:steel_bottle","鉄のボトル"},

	-- Wool
	{"wool:black","黒色の羊毛"},
	{"wool:blue","青色の羊毛"},
	{"wool:brown","茶色の羊毛"},
	{"wool:cyan","空色の羊毛"},
	{"wool:dark_green","緑色の羊毛"},
	{"wool:dark_grey","灰色の羊毛"},
	{"wool:green","黄緑色の羊毛"},
	{"wool:grey","薄灰色の羊毛"},
	{"wool:magenta","赤紫色の羊毛"},
	{"wool:orange","橙色の羊毛"},
	{"wool:pink","桃色の羊毛"},
	{"wool:red","赤色の羊毛"},
	{"wool:violet","紫色の羊毛"},
	{"wool:white","白色の羊毛"},
	{"wool:yellow","黄色の羊毛"},

	-- Xpanes
	{"xpanes:bar","鉄の棒"},
	{"xpanes:pane","ガラス板"},
}
