-- Licence for this file and translations: CC0

return {
	-- core
	{"air",						"Воздух (Вы читер!)"},
	{"ignore",					"Игнор (Вы читер!)"},

	-- boat
	{"boats:boat",					"Лодка"},

	-- bedsf
	{"beds:bed",					"Простая кровать"},
	{"beds:fancy_bed",				"Шикарная кровать"},

	-- bones
	{"bones:bones",					"Кость"},
	
	-- bucket
	{"bucket:bucket_empty",				"Ведро"},
	{"bucket:bucket_water",				"Ведро с водой"},
	{"bucket:bucket_river_water",			"Ведро с речной водой"},
	{"bucket:bucket_lava",				"Ведро с лавой"},
	
	-- default
	-- craftitems
	{"default:stick",				"Палка"},
	{"default:paper",				"Бумага"},
	{"default:book",				"Книга"},
	{"default:book_written",			"Книга с текстом"},
	{"default:coal_lump",				"Уголь"},
	{"default:iron_lump",				"Железная руда"},
	{"default:copper_lump",				"Медная руда"},
	{"default:mese_crystal",			"Кристалл Месе"},
	{"default:gold_lump",				"Золотая руда"},
	{"default:diamond",				"Алмаз"},
	{"default:clay_lump",				"Глина"},
	{"default:steel_ingot",				"Слиток стали"},
	{"default:copper_ingot",			"Слиток меди"},
	{"default:bronze_ingot",			"Слиток бронзы"},
	{"default:gold_ingot",				"Слиток золота"},
	{"default:mese_crystal_fragment",		"Фрагмет кристалла Месе"},
	{"default:clay_brick",				"Глиняный кирпич"},
	{"default:scorched_stuff",			"Сожжённая вещь"},
	{"default:obsidian_shard",			"Осколок обсидиана"},
	-- nodes
	{"default:stone",				"Камень"},
	{"default:desert_stone",			"Пустынный камень"},
	{"default:desert_cobble",			"Пустынный булыжник"},
	{"default:stone_with_coal",			"Камень с углём"},
	{"default:stone_with_iron",			"Камень с железом"},
	{"default:stone_with_copper",			"Камень с медью"},
	{"default:stone_with_mese",			"Камень с вкраплениями Месе"},
	{"default:stone_with_gold",			"Камен с золотом"},
	{"default:stone_with_diamond",			"Камень с алмазом"},
	{"default:stonebrick",				"Каменный кирпич"},
	{"default:desert_stonebrick",			"Кирпич из пустынного камня"},
	{"default:dirt_with_grass",			"Земля с травой"},
	{"default:dirt_with_grass_footsteps",		"Земля с травой и следами"},
	{"default:dirt_with_dry_grass",			"Земля с сухой травой"},
	{"default:dirt_with_snow",			"Земля со снегом"},
	{"default:dirt",				"Земля"},
	{"default:sand",				"Песок"},
	{"default:desert_sand",				"Песок пустыни"},
	{"default:gravel",				"Гравий"},
	{"default:sandstone",				"Песчаник"},
	{"default:sandstonebrick",			"Кирпич из песчаника"},
	{"default:clay",				"Глина"},
	{"default:brick",				"Кирпич"},
	{"default:tree",				"Дерево"},
	{"default:jungletree",				"Дерево джунглей"},
	{"default:junglewood",				"Доски джунглей"},
	{"default:jungleleaves",			"Листва джунглей"},
	{"default:junglesapling",			"Саженец джунглей"},
	{"default:junglegrass",				"Трава джунглей"},
	{"default:leaves",				"Листва"},
	{"default:cactus",				"Кактус"},
	{"default:papyrus",				"Папирус"},
	{"default:bookshelf",				"Книжная полка"},
	{"default:glass",				"Стекло"},
	{"default:fence_wood",				"Деревянный забор"},
	{"default:rail",				"Рельс"},
	{"default:ladder",				"Лестница"},
	{"default:wood",				"Деревянные доски"},
	{"default:cloud",				"Облако"},
	{"default:water_flowing",			"Поток воды"},
	{"default:water_source",			"Источник воды"},
	{"default:river_water_flowing",			"Поток речной воды"},
	{"default:river_water_source",			"Источник речной воды"},
	{"default:lava_flowing",			"Поток лавы"},
	{"default:lava_source",				"Источник лавы"},
	{"default:torch",				"Факел"},
	{"default:sign_wall",				"Вывеска"},
	{"default:chest",				"Сундук"},
	{"default:chest_locked",			"Закрытый сундук"},
	{"default:furnace",				"Печь"},
	{"default:furnace_active",			"Печь"},
	{"default:cobble",				"Булыжник"},
	{"default:mossycobble",				"Мшистый булыжник"},
	{"default:coalblock",				"Угольный блок"},
	{"default:steelblock",				"Стальной блок"},
	{"default:copperblock",				"Медный блок"},
	{"default:bronzeblock",				"Бронзовый блок"},
	{"default:mese",				"Месе"},
	{"default:goldblock",				"Золотой блок"},
	{"default:diamondblock",			"Алмазный блок"},
	{"default:obsidian_glass",			"Обсидиановое стекло"},
	{"default:obsidian",				"Обсидиан"},
	{"default:obsidianbrick",			"Обсидиановый кирпич"},
	{"default:nyancat",				"Нянкэт"},
	{"default:nyancat_rainbow",			"Радуга нянкэта"},
	{"default:sapling",				"Саженец"},
	{"default:apple",				"Яблоко"},
	{"default:dry_shrub",				"Сухой куст"},
	{"default:grass_1",				"Трава"},
	{"default:grass_2",				"Трава"},
	{"default:grass_3",				"Трава"},
	{"default:grass_4",				"Трава"},
	{"default:grass_5",				"Трава"},
	{"default:dry_grass_1",				"Сухая трава"},
	{"default:dry_grass_2",				"Сухая трава"},
	{"default:dry_grass_3",				"Сухая трава"},
	{"default:dry_grass_4",				"Сухая трава"},
	{"default:dry_grass_5",				"Сухая трава"},
	{"default:ice",					"Лёд"},
	{"default:snow",				"Снег"},
	{"default:snowblock",				"Снежный блок"},
	{"default:pine_needles",			"Сосновая хвоя"},
	{"default:pine_sapling",			"Сосновый саженец"},
	{"default:pinetree",				"Сосна"},
	{"default:pinewood",				"Сосновые доски"},
	{"default:acacia_leaves",			"Листва акации"},
	{"default:acacia_sapling",			"Саженец акации"},
	{"default:acacia_tree",				"Акация"},
	{"default:acacia_wood",				"Доски акации"},
	{"default:meselamp",				"Лампа Месе"},
	-- tools
	{"default:pick_wood",				"Деревянная кирка"},
	{"default:pick_stone",				"Каменная кирка"},
	{"default:pick_bronze",				"Бронзовая кирка"},
	{"default:pick_steel",				"Стальная кирка"},
	{"default:pick_mese",				"Кирка Месе"},
	{"default:pick_diamond",			"Алмазная кирка"},
	{"default:shovel_wood",				"Деревянная лопата"},
	{"default:shovel_stone",			"Каменная лопата"},
	{"default:shovel_bronze",			"Бронзовая лопата"},
	{"default:shovel_steel",			"Стальная лопата"},
	{"default:shovel_mese",				"Лопата Месе"},
	{"default:shovel_diamond",			"Алмазная лопата"},
	{"default:axe_wood",				"Деревянный топор"},
	{"default:axe_stone",				"Каменный топор"},
	{"default:axe_bronze",				"Бронзовый топор"},
	{"default:axe_steel",				"Стальной топор"},
	{"default:axe_mese",				"Топор Месе"},
	{"default:axe_diamond",				"Алмазный топор"},
	{"default:sword_wood",				"Деревянный меч"},
	{"default:sword_stone",				"Каменный меч"},
	{"default:sword_bronze",			"Бронзовый меч"},
	{"default:sword_steel",				"Стальной меч"},
	{"default:sword_mese",				"Меч Месе"},
	{"default:sword_diamond",			"Алмазный меч"},
	
	-- doors
	{"doors:door_wood",				"Деревянная дверь"},
	{"doors:door_steel",				"Стальная дверь"},
	{"doors:door_glass",				"Стеклянная дверь"},
	{"doors:door_obsidian_glass",			"Дверь из обсидианового стекла"},
	{"doors:trapdoor",				"Люк"},
	
	-- dye
	{"dye:white",					"Белый краситель"},
	{"dye:grey",					"Серый краситель"},
	{"dye:dark_grey",				"Тёмно-серый краситель"},
	{"dye:black",					"Чёрный краситель"},
	{"dye:violet",					"Фиолетовый краситель"},
	{"dye:blue",					"Синий краситель"},
	{"dye:cyan",					"Голубой краситель"},
	{"dye:dark_green",				"Тёмно-зелёный краситель"},
	{"dye:green",					"Зелёный краситель"},
	{"dye:yellow",					"Жёлтый краситель"},
	{"dye:brown",					"Коричневый краситель"},
	{"dye:orange",					"Оранжевый краситель"},
	{"dye:red",					"Красный краситель"},
	{"dye:magenta",					"Пурпурный краситель"},
	{"dye:pink",					"Розовый краситель"},
	
	-- farming
	{"farming:straw",				"Солома"},
	{"farming:soil",				"Почва"},
	{"farming:soil_wet",				"Влажная почва"},
	{"farming:cotton",				"Хлопок"},
	{"farming:cotton_1",				"Хлопчатник"},
	{"farming:cotton_2",				"Хлопчатник"},
	{"farming:cotton_3",				"Хлопчатник"},
	{"farming:cotton_4",				"Хлопчатник"},
	{"farming:cotton_5",				"Хлопчатник"},
	{"farming:sting",				"Нить"},
	{"farming:hoe_wood",				"Деревянная мотыга"},
	{"farming:hoe_stone",				"Каменная мотыга"},
	{"farming:hoe_steel",				"Стальная мотыга"},
	{"farming:hoe_bronze",				"Бронзовая мотыга"},
	{"farming:hoe_mese",				"Мотыга Месе"},
	{"farming:hoe_diamond",				"Алмазная мотыга"},
	{"farming:seed_wheat",				"Семена пшаницы"},
	{"farming:seed_cotton",				"Семена хлопка"},
	{"farming:wheat",				"Пшеница"},
	{"farming:wheat_1",				"Пшеница"},
	{"farming:wheat_2",				"Пшеница"},
	{"farming:wheat_3",				"Пшеница"},
	{"farming:wheat_4",				"Пшеница"},
	{"farming:wheat_5",				"Пшеница"},
	{"farming:wheat_6",				"Пшеница"},
	{"farming:wheat_7",				"Пшеница"},
	{"farming:wheat_8",				"Пшеница"},
	{"farming:flour",				"Мука"},
	{"farming:bread",				"Хлеб"},
	
	-- fire
	{"fire:basic_flame",				"Огонь"},
	
	-- flowers
	{"flowers:dandelion_white",			"Белый одуванчик"},
	{"flowers:dandelion_yellow",			"Жёлтый одуванчик"},
	{"flowers:geranium",				"Герань"},
	{"flowers:rose",				"Роза"},
	{"flowers:tulip",				"Тюльпан"},
	{"flowers:viola",				"Фиалка"},
	{"flowers:mushroom_red",			"Красный гриб"},
	{"flowers:mushroom_brown",			"Коричневый гриб"},
	{"flowers:mushroom_spores_red",			"Споры красного гриба"},
	{"flowers:mushroom_spores_brown",		"Споры коричневого гриба"},
	
	-- nodetest
	{"nodetest:bone",				"Кость"},
	{"nodetest:desert_sandstone",			"Пустынный песчаник"},
	{"nodetest:rock",				"Скальный камень"},
	{"nodetest:tree_horizontal",			"Горизонтальное дерево"},
	{"nodetest:jungletree_horizontal",		"Горизонтальное дерево джунглей"},
	{"nodetest:papyrus_roots",			"Корни папируса"},
	{"nodetest:conifersapling",			"Саженец хвойного дерева"},
	{"nodetest:conifertree",			"Хвойное дерево"},
	{"nodetest:coniferleaves_1",			"Листва хвойного дерева"},
	{"nodetest:coniferleaves_2",			"Листва хвойного дерева"},
	{"nodetest:conifertree_horizontal",		"Горизонтальное хвойное дерево"},
	{"nodetest:spearwood",				"Деревянное копьё"},
	{"nodetest:spearstone",				"Каменное копьё"},
	
	-- pots
	{"pots:pot",					"Цветочный горшок"},
	{"pots:cactus",					"Кактус в горшке"},
	{"pots:dandelion_white",			"Белый одуванчик в горшке"},
	{"pots:dandelion_yellow",			"Жёлтый одуванчик в горшке"},
	{"pots:geranium",				"Герань в горшке"},
	{"pots:rose",					"Роза в горшке"},
	{"pots:tulip",					"Тюльпан в горшке"},
	{"pots:viola",					"Фиалка в горшке"},
	
	-- screwdriver
	{"screwdriver:screwdriver",			"Отвёртка"},

	-- stairs
	{"stairs:stair_wood",				"Деревянная ступенька"},
	{"stairs:stair_junglewood",			"Ступенька из дерева джунглей"},
	{"stairs:stair_pinewood",			"Сосновая лестница"},
	{"stairs:stair_acacia_wood",			"Сосновая из акации"},
	{"stairs:stair_stone",				"Каменная ступенька"},
	{"stairs:stair_cobble",				"Ступенька из булыжника"},
	{"stairs:stair_stonebrick",			"Ступенька из каменного кирпича"},
	{"stairs:stair_sandstone",			"Ступенька из песчаника"},
	{"stairs:stair_sandstonebrick",			"Ступенька из песчаного кирпича"},
	{"stairs:stair_brick",				"Кирпичная ступенька"},
	{"stairs:stair_desert_stone",			"Ступенька из пустынного камня"},
	{"stairs:stair_desert_cobble",			"Ступенька из пустынного булыжника"},
	{"stairs:stair_desert_stonebrick",		"Ступенька из пустынного каменного кирпича"},
	{"stairs:stair_obsidian",			"Обсидиановая ступенька"},
	{"stairs:stair_obsidianbrick",			"Ступенька из обсидианового кирпича"},
	{"stairs:stair_straw",				"Соломенная ступенька"},
	{"stairs:stair_steelblock",			"Стальная ступенька"},
	{"stairs:stair_copperblock",			"Медная ступенька"},
	{"stairs:stair_bronzeblock",			"Бронзовая ступенька"},
	{"stairs:stair_goldblock",			"Золотая ступенька"},

	{"stairs:slab_wood",				"Деревянная плита"},
	{"stairs:slab_junglewood",			"Плита из дерева джунглей"},
	{"stairs:slab_pinewood",			"Сосновая плита"},
	{"stairs:slab_acacia_wood",			"Плита из акации"},
	{"stairs:slab_stone",				"Каменная плита"},
	{"stairs:slab_cobble",				"Плита из булыжника"},
	{"stairs:slab_stonebrick",			"Плита из каменного кирпича"},
	{"stairs:slab_sandstone",			"Плита из песчаника"},
	{"stairs:slab_sandstonebrick",			"Плита из песчаного кирпича"},
	{"stairs:slab_brick",				"Кирпичная плита"},
	{"stairs:slab_desert_stone",			"Плита из пустынного камня"},
	{"stairs:slab_desert_cobble",			"Плита из пустынного булыжника"},
	{"stairs:slab_desert_stonebrick",		"Плита из пустынного каменного кирпича"},
	{"stairs:slab_obsidian",			"Обсидиановая плита"},
	{"stairs:slab_obsidianbrick",			"Плита из обсидианового кирпича"},
	{"stairs:slab_straw", 				"Соломенная плита"},
	{"stairs:slab_steelblock",			"Стальная плита"},
	{"stairs:slab_copperblock",			"Медная плита"},
	{"stairs:slab_bronzeblock",			"Бронзовая плита"},
	{"stairs:slab_goldblock", 			"Золотая плита"},

	-- tnt
	{"tnt:tnt",					"Динамит"},
	{"tnt:gunpowder",				"Порох"},
	
	-- wool
	{"wool:white",					"Белая шерсть"},
	{"wool:grey",					"Серая шерсть"},
	{"wool:dark_grey",				"Тёмно-серая шерсть"},
	{"wool:black",					"Чёрная шерсть"},
	{"wool:violet",					"Фиолетовая шерсть"},
	{"wool:blue",					"Синяя шерсть"},
	{"wool:cyan",					"Голубая шерсть"},
	{"wool:dark_green",				"Тёмнозелёная шерсть"},
	{"wool:green",					"Зелёная шерсть"},
	{"wool:yellow",					"Жёлтая шерсть"},
	{"wool:brown",					"Коричневая шерсть"},
	{"wool:orange",					"Оранжевая шерсть"},
	{"wool:red",					"Красная шерсть"},
	{"wool:magenta",				"Пурпурная шерсть"},
	{"wool:pink",					"Розовая шерсть"},

	-- vessels
	{"vessels:glass_bottle",			"Стеклянная бутылка"},
	{"vessels:drinking_glass",			"Стакан"},
	{"vessels:steel_bottle",			"Стальная бутылка"},
	{"vessels:glass_fragments",			"Битое стекло"},
	{"vessels:shelf",				"Полка"},

	-- xpanes
	{"xpanes:bar",					"Железный прут"},
	{"xpanes:pane",					"Панель"},
}

