return {
	-- beds
	{"beds:bed",					""},

	-- bones
	{"bones:bones",					""},
	
	-- bucket
	{"bucket:bucket_empty",				""},
	{"bucket:bucket_water",				""},
	{"bucket:bucket_lava",				""},

	-- carts
	{"carts:cart",					""},
	{"carts:powerrail",				""},
	{"carts:brakerail",				""},
	
	-- default
	-- craftitems
	{"default:stick",					""},
	{"default:paper",					""},
	{"default:book",					""},
	{"default:coal_lump",				""},
	{"default:iron_lump",				""},
	{"default:copper_lump",				""},
	{"default:mese_crystal",				""},
	{"default:gold_lump",				""},
	{"default:diamond",					""},
	{"default:clay_lump",				""},
	{"default:steel_ingot",				""},
	{"default:copper_ingot",				""},
	{"default:bronze_ingot",				""},
	{"default:gold_ingot",				""},
	{"default:mese_crystal_fragment",		""},
	{"default:clay_brick",				""},
	{"default:scorched_stuff",			""},
	{"default:obsidian_shard",			""},
	-- nodes
	{"default:stone",					""},
	{"default:desert_stone",				""},
	{"default:stone_with_coal",			""},
	{"default:stone_with_iron",			""},
	{"default:stone_with_copper",			""},
	{"default:stone_with_mese",			""},
	{"default:stone_with_gold",			""},
	{"default:stone_with_diamond",		""},
	{"default:stone_stonebrick",			""},
	{"default:stone_desert_stonebrick",	""},
	{"default:dirt_with_grass",			""},
	{"default:dirt_with_grass_footsteps",	""},
	{"default:dirt_with_snow",			""},
	{"default:dirt",					""},
	{"default:sand",					""},
	{"default:desert_sand",				""},
	{"default:gravel",					""},
	{"default:sandstone",				""},
	{"default:sandstonebrick",			""},
	{"default:clay",					""},
	{"default:brick",					""},
	{"default:tree",					""},
	{"default:jungletree",				""},
	{"default:junglewood",				""},
	{"default:jungleleaves",				""},
	{"default:junglesapling",			""},
	{"default:junglegrass",				""},
	{"default:leaves",					""},
	{"default:cactus",					""},
	{"default:papyrus",					""},
	{"default:bookshelf",				""},
	{"default:glass",					""},
	{"default:fence_wood",				""},
	{"default:rail",					""},
	{"default:ladder",					""},
	{"default:wood",					""},
	{"default:cloud",					""},
	{"default:water_flowing",			""},
	{"default:water_source",				""},
	{"default:lava_flowing",				""},
	{"default:lava_source",				""},
	{"default:torch",					""},
	{"default:sign_wall",				""},
	{"default:chest",					""},
	{"default:chest_locked",				""},
	{"default:furnace",					""},
	{"default:furnace_active",			""},
	{"default:cobble",					""},
	{"default:mossycobble",				""},
	{"default:coalblock",				""},
	{"default:steelblock",				""},
	{"default:copperblock",				""},
	{"default:bronzeblock",				""},
	{"default:mese",					""},
	{"default:goldblock",				""},
	{"default:diamondblock",				""},
	{"default:obsidian_glass",			""},
	{"default:obsidian",				""},
	{"default:nyancat",					""},
	{"default:nyancat_rainbow",			""},
	{"default:sapling",					""},
	{"default:apple",					""},
	{"default:dry_shrub",				""},
	{"default:grass_1",					""},
	{"default:grass_2",					""},
	{"default:grass_3",					""},
	{"default:grass_4",					""},
	{"default:grass_5",					""},
	{"default:ice",					""},
	{"default:snow",					""},
	{"default:snowblock",				""},
	{"default:coral_skeleton",			""},
	{"default:coral_orange",			""},
	{"default:coral_brown",				""},
	{"default:desert_stone_block",			""},
	{"default:desert_sandstone",			""},
	{"default:desert_sandstone_block",		""},
	{"default:desert_sandstone_brick",		""},
	{"default:dirt_with_rainforest_litter",		""},
	{"default:fence_junglewood",			""},
	{"default:fence_aspen_wood",			""},
	{"default:fence_acacia_wood",			""},
	{"default:fence_pine_wood",			""},
	{"default:acacia_bush_leaves",			""},
	{"default:acacia_bush_sapling",			""},
	{"default:acacia_bush_stem",			""},
	{"default:aspen_leaves",			""},
	{"default:aspen_sapling",			""},
	{"default:aspen_tree",				""},
	{"default:aspen_wood",				""},
	{"default:bush_leaves",				""},
	{"default:bush_sapling",			""},
	{"default:bush_stem",				""},
	{"default:tin_lump",				""},
	{"default:tin_ingot",				""},
	{"default:stone_block",				""},
	{"default:stone_with_tin",			""},
	{"default:sandstone_block",			""},
	{"default:silver_sand",				""},
	{"default:silver_sandstone",			""},
	{"default:silver_sandstone_block",		""},
	{"default:silver_sandstone_brick",		""},
	{"default:ladder_steel",			""},
	{"default:tinblock",				""},
	{"default:obsidian_block",			""},
	{"default:mese_post_light",			""},
	-- tools
	{"default:pick_wood",				""},
	{"default:pick_stone",				""},
	{"default:pick_copper",				""},
	{"default:pick_steel",				""},
	{"default:pick_mese",				""},
	{"default:shovel_wood",				""},
	{"default:shovel_stone",				""},
	{"default:shovel_copper",			""},
	{"default:shovel_steel",				""},
	{"default:axe_wood",				""},
	{"default:axe_stone",				""},
	{"default:axe_copper",				""},
	{"default:axe_steel",				""},
	{"default:sword_wood",				""},
	{"default:sword_stone",				""},
	{"default:sword_copper",				""},
	{"default:sword_steel",				""},
	{"default:skeleton_key",			""},
	
	-- doors
	{"doors:door_wood",					""},
	{"doors:door_steel",				""},
	{"doors:trapdoor_steel",			""},
	{"doors:gate_junglewood_closed",		""},
	{"doors:gate_aspen_wood_closed",		""},
	{"doors:gate_acacia_wood_closed",		""},
	{"doors:gate_pine_wood_closed",			""},
	{"doors:gate_wood_closed",			""},
	
	-- dye
	{"dye:white",						""},
	{"dye:grey",						""},
	{"dye:dark_grey",					""},
	{"dye:black",						""},
	{"dye:violet",						""},
	{"dye:blue",						""},
	{"dye:cyan",						""},
	{"dye:dark_green",					""},
	{"dye:green",						""},
	{"dye:yellow",						""},
	{"dye:brown",						""},
	{"dye:orange",						""},
	{"dye:red",						""},
	{"dye:magenta",					""},
	{"dye:pink",						""},
	
	-- farming
	{"farming:soil",					""},
	{"farming:soil_wet",				""},
	{"farming:seed_cotton",				""},
	{"farming:cotton",					""},
	{"farming:cotton_1",				""},
	{"farming:cotton_2",				""},
	{"farming:cotton_3",				""},
	{"farming:cotton_4",				""},
	{"farming:cotton_5",				""},
	{"farming:string",					""},
	{"farming:hoe_wood",				""},
	{"farming:hoe_stone",				""},
	{"farming:hoe_steel",				""},
	{"farming:hoe_bronze",				""},
	{"farming:hoe_mese",				""},
	{"farming:weed",					""},
	{"farming:seed_wheat",				""},
	{"farming:wheat",					""},
	{"farming:wheat_1",					""},
	{"farming:wheat_2",					""},
	{"farming:wheat_3",					""},
	{"farming:wheat_4",					""},
	{"farming:wheat_5",					""},
	{"farming:wheat_6",					""},
	{"farming:wheat_7",					""},
	{"farming:wheat_8",					""},
	{"farming:flour",					""},
	{"farming:dough",					""},
	{"farming:bread",					""},
	
	-- fire
	{"fire:basic_flame",				""},
	{"fire:permanent_flame",			""},
	{"fire:flint_and_steel",			""},
	
	-- flowers
	{"flowers:dandelion_white",			""},
	{"flowers:dandelion_yellow",			""},
	{"flowers:geranium",				""},
	{"flowers:rose",					""},
	{"flowers:tulip",					""},
	{"flowers:viola",					""},
	{"flowers:waterlily",				""},
	
	-- nodetest
	{"nodetest:bone",					""},
	{"nodetest:rock",					""},
	{"nodetest:tree_horizontal",			""},
	{"nodetest:jungletree_horizontal",		""},
	{"nodetest:papyrus_roots",			""},
--	{"nodetest:conifersapling",			""},
--	{"nodetest:conifertree",				""},
--	{"nodetest:coniferleaves_1",			""},
--	{"nodetest:coniferleaves_2",			""},
--	{"nodetest:conifertree_horizontal",	""},
	{"nodetest:spearwood",				""},
	{"nodetest:spearstone",				""},
	
	-- pots
--	{"pots:pot",						""},
--	{"pots:cactus",					""},
--	{"pots:dandelion_white",				""},
--	{"pots:dandelion_yellow",			""},
--	{"pots:geranium",					""},
--	{"pots:rose",						""},
--	{"pots:tulip",						""},
--	{"pots:viola",						""},
	
	-- screwdriver
	{"screwdriver:screwdriver",			""},
--	{"screwdriver:screwdriver1",			""},
--	{"screwdriver:screwdriver2",			""},
--	{"screwdriver:screwdriver3",			""},
--	{"screwdriver:screwdriver4",			""},
	
	-- stairs
	{"stairs:slab_aspen_wood",			""},
	{"stairs:stair_ice",				""},
	{"stairs:stair_snowblock",			""},
	{"stairs:stair_aspen_wood",			""},
	{"stairs:stair_stone_block",			""},
	{"stairs:stair_mossycobble",			""},
	{"stairs:stair_silver_sandstone",		""},
	{"stairs:stair_silver_sandstone_block",		""},
	{"stairs:stair_silver_sandstone_brick",		""},
	{"stairs:stair_sandstone_block",		""},
	{"stairs:stair_desert_sandstone",		""},
	{"stairs:stair_desert_sandstone_block",		""},
	{"stairs:stair_desert_sandstone_brick",		""},
	{"stairs:stair_desert_stone_block",		""},
	{"stairs:stair_obsidian_block",			""},
	{"stairs:slab_ice",				""},
	{"stairs:slab_snowblock",			""},
	{"stairs:slab_stone_block",			""},
	{"stairs:slab_mossycobble",			""},
	{"stairs:slab_silver_sandstone",		""},
	{"stairs:slab_silver_sandstone_block",		""},
	{"stairs:slab_silver_sandstone_brick",		""},
	{"stairs:slab_sandstone_block",			""},
	{"stairs:slab_desert_stone_block",		""},
	{"stairs:slab_desert_sandstone",		""},
	{"stairs:slab_desert_sandstone_block",		""},
	{"stairs:slab_desert_sandstone_brick",		""},
	{"stairs:slab_obsidian_block",			""},

	-- wool
	{"wool:white",						""},
	{"wool:grey",						""},
	{"wool:dark_grey",					""},
	{"wool:black",						""},
	{"wool:violet",					""},
	{"wool:blue",						""},
	{"wool:cyan",						""},
	{"wool:dark_green",					""},
	{"wool:green",						""},
	{"wool:yellow",					""},
	{"wool:brown",						""},
	{"wool:orange",					""},
	{"wool:red",						""},
	{"wool:magenta",					""},
	{"wool:pink",						""},

	-- vessels
	{"vessels:glass_bottle",				""},
	{"vessels:drinking_glass",			""},
	{"vessels:steel_bottle",				""},
	{"vessels:glass_fragments",			""},

	-- walls
	{"walls:cobble",				""},
	{"walls:mossycobble",				""},
	{"walls:desertcobble",				""},

	-- xpanes
	{"xpanes:bar_flat",				""},
	{"xpanes:pane_flat",				""},
}

