vortoj.sample_language = {
	-- bones
	{"bones:bones",					""}
	
	-- bucket
	{"bucket:bucket_empty",				""}
	{"bucket:bucket_water",				""}
	{"bucket:bucket_lava",				""}
	
	-- default
	-- craftitems
	{"default:stick",					""}
	{"default:paper",					""}
	{"default:book",					""}
	{"default:coal_lump",				""}
	{"default:iron_lump",				""}
	{"default:copper_lump",				""}
	{"default:mese_crystal",				""}
	{"default:clay_lump",				""}
	{"default:steel_ingot",				""}
	{"default:copper_ingot",				""}
	{"default:mese_crystal_fragment",		""}
	{"default:clay_brick",				""}
	{"default:scorched_stuff",			""}
	-- nodes
	{"default:stone",					""}
	{"default:desert_stone",				""}
	{"default:stone_with_coal",			""}
	{"default:stone_with_iron",			""}
	{"default:stone_with_copper",			""}
	{"default:stone_with_mese",			""}
	{"default:dirt_with_grass",			""}
	{"default:dirt_with_grass_footsteps",	""}
	{"default:dirt_with_snow",			""}
	{"default:dirt",					""}
	{"default:sand",					""}
	{"default:desert_sand",				""}
	{"default:gravel",					""}
	{"default:sandstone",				""}
	{"default:clay",					""}
	{"default:brick",					""}
	{"default:tree",					""}
	{"default:jungletree",				""}
	{"default:jungleleaves",				""}
	{"default:junglesapling",			""}
	{"default:junglegrass",				""}
	{"default:leaves",					""}
	{"default:cactus",					""}
	{"default:papyrus",					""}
	{"default:bookshelf",				""}
	{"default:glass",					""}
	{"default:fence_wood",				""}
	{"default:rail",					""}
	{"default:ladder",					""}
	{"default:wood",					""}
	{"default:cloud",					""}
	{"default:water_flowing",			""}
	{"default:water_source",				""}
	{"default:lava_flowing",				""}
	{"default:lava_source",				""}
	{"default:torch",					""}
	{"default:sign_wall",				""}
	{"default:chest",					""}
	{"default:chest_locked",				""}
	{"default:furnace",					""}
	{"default:furnace_active",			""}
	{"default:cobble",					""}
	{"default:mossycobble",				""}
	{"default:coalblock",				""}
	{"default:steelblock",				""}
	{"default:copperblock",				""}
	{"default:mese",					""}
	{"default:nyancat",					""}
	{"default:nyancat_rainbow",			""}
	{"default:sapling",					""}
	{"default:apple",					""}
	{"default:dry_shrub",				""}
	{"default:grass_1",					""}
	{"default:grass_2",					""}
	{"default:grass_3",					""}
	{"default:grass_4",					""}
	{"default:grass_5",					""}
	{"default:ice",					""}
	{"default:snow",					""}
	{"default:snowblock",				""}
	-- tools
	{"default:pick_wood",				""}
	{"default:pick_stone",				""}
	{"default:pick_copper",				""}
	{"default:pick_steel",				""}
	{"default:pick_mese",				""}
	{"default:shovel_wood",				""}
	{"default:shovel_stone",				""}
	{"default:shovel_copper",			""}
	{"default:shovel_steel",				""}
	{"default:axe_wood",				""}
	{"default:axe_stone",				""}
	{"default:axe_copper",				""}
	{"default:axe_steel",				""}
	{"default:sword_wood",				""}
	{"default:sword_stone",				""}
	{"default:sword_copper",				""}
	{"default:sword_steel",				""}
	
	-- doors
	{"doors:door_wood",					""}
	{"doors:door_steel",				""}
	
	-- dye
	{"dye:white",						""}
	{"dye:grey",						""}
	{"dye:dark_grey",					""}
	{"dye:black",						""}
	{"dye:violet",						""}
	{"dye:blue",						""}
	{"dye:cyan",						""}
	{"dye:dark_green",					""}
	{"dye:green",						""}
	{"dye:yellow",						""}
	{"dye:brown",						""}
	{"dye:orange",						""}
	{"dye:red",						""}
	{"dye:magenta",					""}
	{"dye:pink",						""}
	
	-- farming
	{"farming:cotton",					""}
	{"farming:cotton_1",				""}
	{"farming:cotton_2",				""}
	{"farming:cotton_3",				""}
	{"farming:cotton_4",				""}
	{"farming:cotton_5",				""}
	{"farming:sting",					""}
	{"farming:hoe_wood",				""}
	{"farming:hoe_stone",				""}
	{"farming:hoe_steel",				""}
	{"farming:hoe_mese",				""}
	{"farming:weed",					""}
	{"farming:wheat",					""}
	{"farming:wheat_1",					""}
	{"farming:wheat_2",					""}
	{"farming:wheat_3",					""}
	{"farming:wheat_4",					""}
	{"farming:wheat_5",					""}
	{"farming:wheat_6",					""}
	{"farming:wheat_7",					""}
	{"farming:wheat_8",					""}
	{"farming:flour",					""}
	{"farming:dough",					""}
	{"farming:bread",					""}
	
	-- fire
	{"fire:basic_flame",				""}
	
	-- flowers
	{"flowers:dandelion_white",			""}
	{"flowers:dandelion_yellow",			""}
	{"flowers:geranium",				""}
	{"flowers:rose",					""}
	{"flowers:tulip",					""}
	{"flowers:viola",					""}
	
	-- nodetest
	{"nodetest:bone",					""}
	{"nodetest:desert_sandstone",			""}
	{"nodetest:rock",					""}
	{"nodetest:tree_horizontal",			""}
	{"nodetest:jungletree_horizontal",		""}
	{"nodetest:papyrus_roots",			""}
	{"nodetest:conifersapling",			""}
	{"nodetest:conifertree",				""}
	{"nodetest:coniferleaves_1",			""}
	{"nodetest:coniferleaves_2",			""}
	{"nodetest:conifertree_horizontal",	""}
	{"nodetest:spearwood",				""}
	{"nodetest:spearstone",				""}
	
	-- pots
	{"pots:pot",						""}
	{"pots:cactus",					""}
	{"pots:dandelion_white",				""}
	{"pots:dandelion_yellow",			""}
	{"pots:geranium",					""}
	{"pots:rose",						""}
	{"pots:tulip",						""}
	{"pots:viola",						""}
	{"pots:viola",						""}
	
	-- screwdriver
	{"screwdriver:screwdriver",			""}
	{"screwdriver:screwdriver_1",			""}
	{"screwdriver:screwdriver_2",			""}
	{"screwdriver:screwdriver_3",			""}
	{"screwdriver:screwdriver_4",			""}
	
	-- wool
	{"wool:white",						""}
	{"wool:grey",						""}
	{"wool:dark_grey",					""}
	{"wool:black",						""}
	{"wool:violet",					""}
	{"wool:blue",						""}
	{"wool:cyan",						""}
	{"wool:dark_green",					""}
	{"wool:green",						""}
	{"wool:yellow",					""}
	{"wool:brown",						""}
	{"wool:orange",					""}
	{"wool:red",						""}
	{"wool:magenta",					""}
	{"wool:pink",						""}
}
