-- toki pona
vortoj = {
	-- beds
	{"beds:bed",					"supa lape"},

	-- bones
	{"bones:bones",					"jan moli"},
	
	-- bucket
	{"bucket:bucket_empty",				"poki telo li ala"},
	{"bucket:bucket_water",				"poki telo li jo telo"},
	{"bucket:bucket_lava",				"poki telo li jo telo kiwen seli"},

	-- carts
	{"carts:cart",					"tomo tawa"},
	{"carts:powerrail",				"nasin pi kiwen suno li monsi"},
	{"carts:brakerail",				"nasin pi kiwen suno li kama"},

	
	-- default
	-- craftitems
	{"default:stick",				"palisa"},
	{"default:paper",				"lipu"},
	{"default:book",				"lipu mute"},
	{"default:coal_lump",				"kiwen pi ko pimeja"},
	{"default:iron_lump",				"kiwen suno wawa li sin"},
	{"default:copper_lump",				"kiwen suno laso li sin"},
	{"default:mese_crystal",			"kiwen nasa lili"},
	{"default:gold_lump",				"kiwen suno jelo li sin"},
	{"default:diamond",				"kiwen wawa mute"},
	{"default:clay_lump",				"ko"},
	{"default:steel_ingot",				"kiwen suno wawa"},
	{"default:copper_ingot",			"kiwen suno laso"},
	{"default:bronze_ingot",			"kiwen suno jelo loje"},
	{"default:gold_ingot",				"kiwen suno jelo"},
	{"default:mese_crystal_fragment",		"kiwen nasa pi lili mute"},
	{"default:clay_brick",				""},
	{"default:scorched_stuff",			"ko jake"},
	{"default:obsidian_shard",			"kiwen pimeja mute lili"},
	-- nodes
	{"default:stone",				"kiwen"},
	{"default:desert_stone",			"kiwen loje"},
	{"default:stone_with_coal",			""},
	{"default:stone_with_iron",			""},
	{"default:stone_with_copper",			""},
	{"default:stone_with_mese",			""},
	{"default:stone_with_gold",			""},
	{"default:stone_with_diamond",			""},
	{"default:stone_stonebrick",			""},
	{"default:stone_desert_stonebrick",		""},
	{"default:dirt_with_grass",			"ko ma en kasi"},
	{"default:dirt_with_grass_footsteps",		"ko ma en kasi en noka"},
	{"default:dirt_with_snow",			"ko ma en ko telo lete"},
	{"default:dirt",				"ko ma"},
	{"default:sand",				"ko kiwen lili"},
	{"default:desert_sand",				"ko kiwen lili loje"},
	{"default:gravel",				"ko kiwen"},
	{"default:sandstone",				"kiwen pi ko kiwen"},
	{"default:sandstonebrick",			""},
	{"default:clay",				"ko"},
	{"default:brick",				"kiwen"},
	{"default:tree",				"kasi"},
	{"default:jungletree",				"kasi"},
	{"default:junglewood",				"kasi"},
	{"default:jungleleaves",			"lipu kasi"},
	{"default:junglesapling",			"kasi lili"},
	{"default:junglegrass",				"kasi anpa"},
	{"default:leaves",				"lipu kasi"},
	{"default:cactus",				"kasi ike"},
	{"default:papyrus",				"kasi lipu"},
	{"default:bookshelf",				"supa lipu"},
	{"default:glass",				"kiwen telo"},
	{"default:fence_wood",				""},
	{"default:rail",				"nasin pi kiwen suno"},
	{"default:ladder",				"nasin sewi"},
	{"default:wood",				""},
	{"default:cloud",				"walo sewi"},
	{"default:water_flowing",			"telo"},
	{"default:water_source",			"telo"},
	{"default:lava_flowing",			"telo pi kiwen seli"},
	{"default:lava_source",				"telo pi kiwen seli"},
	{"default:torch",				"ilo suno"},
	{"default:sign_wall",				"stilen toki"},
	{"default:chest",				"poki"},
	{"default:chest_locked",			"poki"},
	{"default:furnace",				"ilo seli"},
	{"default:furnace_active",			"ilo seli li pali"},
	{"default:cobble",				"kiwen mute"},
	{"default:mossycobble",				"kiwen mute en kasi"},
	{"default:coalblock",				""},
	{"default:steelblock",				""},
	{"default:copperblock",				""},
	{"default:bronzeblock",				""},
	{"default:mese",				"kiwen nasa"},
	{"default:goldblock",				"kiwen jelo"},
	{"default:diamondblock",			""},
	{"default:obsidian_glass",			"kiwen telo pi kiwen pimeja mute"},
	{"default:obsidian",				"kiwen pimeja mute"},
	{"default:nyancat",				"soweli lili pi pan suwi"},
	{"default:nyancat_rainbow",			"sewi kule"},
	{"default:sapling",				"kasi lili"},
	{"default:apple",				"kili"},
	{"default:dry_shrub",				""},
	{"default:grass_1",				"kasi anpa"},
	{"default:grass_2",				"kasi anpa"},
	{"default:grass_3",				"kasi anpa"},
	{"default:grass_4",				"kasi anpa"},
	{"default:grass_5",				"kasi anpa"},
	{"default:ice",					"telo lete"},
	{"default:snow",				"ko pi telo lete"},
	{"default:snowblock",				"ko pi telo lete"},
	-- tools
	{"default:pick_wood",				"ilo pakala pi kasi"},
	{"default:pick_stone",				"ilo pakala pi kiwen"},
	{"default:pick_copper",				"ilo pakala pi kiwen suno laso"},
	{"default:pick_steel",				"ilo pakala pi kiwen suno wawa"},
	{"default:pick_mese",				"ilo pakala nasa"},
	{"default:shovel_wood",				"ilo"},
	{"default:shovel_stone",			"ilo"},
	{"default:shovel_copper",			"ilo"},
	{"default:shovel_steel",			"ilo"},
	{"default:axe_wood",				"ilo"},
	{"default:axe_stone",				"ilo"},
	{"default:axe_copper",				"ilo"},
	{"default:axe_steel",				"ilo"},
	{"default:sword_wood",				"ilo utala"},
	{"default:sword_stone",				"ilo utala"},
	{"default:sword_copper",			"ilo utala"},
	{"default:sword_steel",				"ilo utala"},
	
	-- doors
	{"doors:door_wood",				"lupa tomo"},
	{"doors:door_steel",				"lupa tomo pi kiwen suno"},
	
	-- dye
	{"dye:white",					"kule walo"},
	{"dye:grey",					"kule walo pimeja"},
	{"dye:dark_grey",				"kule pimeja walo"},
	{"dye:black",					"kule pimeja"},
	{"dye:violet",					"kule laso loje"},
	{"dye:blue",					"kule laso"},
	{"dye:cyan",					"kule laso jelo"},
	{"dye:dark_green",				"kule jelo kasi pimeja"},
	{"dye:green",					"kule jelo kasi"},
	{"dye:yellow",					"kule jelo"},
	{"dye:brown",					"kule pi ma jaki"},
	{"dye:orange",					"kule jelo loje"},
	{"dye:red",					"kule loje"},
	{"dye:magenta",					"kule loje laso"},
	{"dye:pink",					"kule loje laso pi jelo ala"},
	
	-- farming
	{"farming:soil",				"ma kasi"},
	{"farming:soil_wet",				"ma kasi telo"},
	{"farming:seed_cotton",				"kasi lili pi kasi soweli"},
	{"farming:cotton",				"kasi soweli"},
	{"farming:cotton_1",				"kasi soweli"},
	{"farming:cotton_2",				"kasi soweli"},
	{"farming:cotton_3",				"kasi soweli"},
	{"farming:cotton_4",				"kasi soweli"},
	{"farming:cotton_5",				"kasi soweli"},
	{"farming:string",				"linja"},
	{"farming:hoe_wood",				"ilo pi ma kasi"},
	{"farming:hoe_stone",				"ilo kiwen pi ma kasi"},
	{"farming:hoe_steel",				"ilo pi ma kasi"},
	{"farming:hoe_bronze",				"ilo pi ma kasi"},
	{"farming:hoe_mese",				"ilo nasa pi ma kasi"},
	{"farming:weed",				"kasi jaki"},
	{"farming:seed_wheat",				"kasi lili pi kasi pan"},
	{"farming:wheat",				"pan"},
	{"farming:wheat_1",				"kasi pan"},
	{"farming:wheat_2",				"kasi pan"},
	{"farming:wheat_3",				"kasi pan"},
	{"farming:wheat_4",				"kasi pan"},
	{"farming:wheat_5",				"kasi pan"},
	{"farming:wheat_6",				"kasi pan"},
	{"farming:wheat_7",				"kasi pan"},
	{"farming:wheat_8",				"kasi pan"},
	{"farming:flour",				"ko pan"},
	{"farming:dough",				"ko pan lete"},
	{"farming:bread",				"pan moku"},
	
	-- fire
	{"fire:basic_flame",				"seli"},
	
	-- flowers
	{"flowers:dandelion_white",			"kasi walo"},
	{"flowers:dandelion_yellow",			"kasi jelo"},
	{"flowers:geranium",				"kasi laso"},
	{"flowers:rose",				"kasi loje"},
	{"flowers:tulip",				"kasi jelo loje"},
	{"flowers:viola",				"kasi laso loje"},
	
	-- nodetest
	{"nodetest:bone",				"palisa pi jan moli"},
	{"nodetest:desert_sandstone",			""},
	{"nodetest:rock",				""},
	{"nodetest:tree_horizontal",			""},
	{"nodetest:jungletree_horizontal",		""},
	{"nodetest:papyrus_roots",			""},
	{"nodetest:conifersapling",			""},
	{"nodetest:conifertree",			""},
	{"nodetest:coniferleaves_1",			""},
	{"nodetest:coniferleaves_2",			""},
	{"nodetest:conifertree_horizontal",		""},
	{"nodetest:spearwood",				""},
	{"nodetest:spearstone",				""},
	
	-- pots
	{"pots:pot",					""},
	{"pots:cactus",					""},
	{"pots:dandelion_white",			""},
	{"pots:dandelion_yellow",			""},
	{"pots:geranium",				""},
	{"pots:rose",					""},
	{"pots:tulip",					""},
	{"pots:viola",					""},
	
	-- screwdriver
	{"screwdriver:screwdriver",			""},
	{"screwdriver:screwdriver1",			""},
	{"screwdriver:screwdriver2",			""},
	{"screwdriver:screwdriver3",			""},
	{"screwdriver:screwdriver4",			""},
	
	-- wool
	{"wool:white",					"len walo"},
	{"wool:grey",					"len walo pimeja"},
	{"wool:dark_grey",				"len pimeja walo"},
	{"wool:black",					"len pimeja"},
	{"wool:violet",					"len"},
	{"wool:blue",					"len"},
	{"wool:cyan",					"len"},
	{"wool:dark_green",				"len"},
	{"wool:green",					"len"},
	{"wool:yellow",					"len"},
	{"wool:brown",					"len"},
	{"wool:orange",					"len"},
	{"wool:red",					"len"},
	{"wool:magenta",				"len"},
	{"wool:pink",					"len"},

	-- vessels
	{"vessels:glass_bottle",			""},
	{"vessels:drinking_glass",			""},
	{"vessels:steel_bottle",			""},
	{"vessels:glass_fragments",			""},
}
