-- toki pona
-- Licence for this file and translations: CC0

return {
	-- beds
	{"beds:bed",					"supa lape"},

	-- bones
	{"bones:bones",					"palisa pi jan moli"},
	
	-- bucket
	{"bucket:bucket_empty",				"poki"},
	{"bucket:bucket_water",				"poki telo"},
	{"bucket:bucket_lava",				"poki pi telo kiwen seli"},

	-- carts
	{"carts:cart",					"poki tawa"},
	{"carts:powerrail",				"nasin pi poki tawa pi wawa mute"},
	{"carts:brakerail",				"nasin pi poki tawa pi pini tawa"},

	
	-- default
	-- craftitems
	{"default:stick",				"palisa"},
	{"default:paper",				"lipu"},
	{"default:book",				"lipu mute"},
	{"default:coal_lump",				"kiwen pimeja"},
	{"default:iron_lump",				"kiwen walo"},
	{"default:copper_lump",				"kiwen pimeja loje"},
	{"default:mese_crystal",			"kiwen nasa lili"},
	{"default:gold_lump",				"kiwen jelo"},
	{"default:diamond",				"kiwen laso"},
	{"default:clay_lump",				"ijo ko"},
	{"default:steel_ingot",				"palisa pi kiwen walo"},
	{"default:copper_ingot",			"palisa pi kiwen pimeja loje"},
	{"default:bronze_ingot",			"palisa pi kiwen loje jelo"},
	{"default:gold_ingot",				"palisa pi kiwen jelo"},
	{"default:mese_crystal_fragment",		"kiwen lili pi kiwen nasa"},
	{"default:clay_brick",				"kiwen ko"},
	{"default:scorched_stuff",			"ko jaki seli"},
	{"default:obsidian_shard",			"kiwen lili pi kiwen wawa pimeja"},
	-- nodes
	{"default:stone",				"kiwen"},
	{"default:desert_stone",			"kiwen jelo pi ma seli"},
	{"default:stone_with_coal",			"kiwen poki pi kiwen pimeja"},
	{"default:stone_with_iron",			"kiwen poki pi kiwen walo"},
	{"default:stone_with_copper",			"kiwen poki pi kiwen pimeja loje"},
	{"default:stone_with_mese",			"kiwen poki pi kiwen nasa"},
	{"default:stone_with_gold",			"kiwen poki pi kiwen jelo"},
	{"default:stone_with_diamond",			"kiwen poki pi kiwen laso"},
	{"default:stone_stonebrick",			"kiwen kiwen"},
	{"default:stone_desert_stonebrick",		"kiwen kiwen jelo ma"},
	{"default:dirt_with_grass",			"ko ma pi kasi anpa"},
	{"default:dirt_with_grass_footsteps",		"ko ma pi kasi anpa en ijo noka"},
	{"default:dirt_with_snow",			"ko ma pi ko lete"},
	{"default:dirt",				"ko ma"},
	{"default:sand",				"kiwen lili jelo"},
	{"default:desert_sand",				"kiwen lili jelo pi ma seli"},
	{"default:gravel",				"kiwen lili"},
	{"default:sandstone",				"kiwen pi kiwen lili jelo"},
	{"default:sandstonebrick",			"kiwen kiwen pi kiwen lili jelo"},
	{"default:clay",				"ko"},
	{"default:brick",				"kiwen kiwen"},
	{"default:tree",				"kasi"},
	{"default:jungletree",				"kasi suli suli"},
	{"default:junglewood",				"sijelo pi kasi suli suli"},
	{"default:jungleleaves",			"lipu pi kasi suli suli"},
	{"default:junglesapling",			"kasi lilipi kasi suli suli"},
	{"default:junglegrass",				"kasi anpa pi ma pi kasi mute"},
	{"default:leaves",				"lipu kasi"},
	{"default:cactus",				"kasi pi palisa mute"},
	{"default:papyrus",				"kasi lipu"},
	{"default:bookshelf",				"supa poki pi lipu mute"},
	{"default:glass",				"kiwen pi kule ala"},
	{"default:fence_wood",				"palisa pi sijelo kasi"},
	{"default:rail",				"nasin pi poki tawa"},
	{"default:ladder",				"palisa tawa sewi"},
	{"default:wood",				"sijelo kasi"},
	{"default:cloud",				"kon walo"},
	{"default:water_flowing",			"telo"},
	{"default:water_source",			"open telo"},
	{"default:lava_flowing",			"telo seli kiwen"},
	{"default:lava_source",				"open pi telo seli kiwen"},
	{"default:torch",				"ilo suno"},
	{"default:sign_wall",				"sitelen"},
	{"default:chest",				"poki ijo"},
	{"default:chest_locked",			"poki ijo pi open ala"},
	{"default:furnace",				"poki seli"},
	{"default:furnace_active",			"poki seli seli"},
	{"default:cobble",				"kiwen mute"},
	{"default:mossycobble",				"kiwen mute kasi"},
	{"default:coalblock",				"kiwen pimeja suli"},
	{"default:steelblock",				"kiwen walo suli"},
	{"default:copperblock",				"kiwen pimeja loje suli"},
	{"default:bronzeblock",				"kiwen jelo loje suli"},
	{"default:mese",				"kiwen nasa suli"},
	{"default:goldblock",				"kiwen jelo suli"},
	{"default:diamondblock",			"kiwen laso suli"},
	{"default:obsidian_glass",			"kiwen pi kule ala en pimeja lili"},
	{"default:obsidian",				"kiwen pimeja wawa"},
	{"default:nyancat",				"soweli lili pi pan suwi"},
	{"default:nyancat_rainbow",			"kule seli pi soweli lili"},
	{"default:sapling",				"kasi lili"},
	{"default:apple",				"kili"},
	{"default:dry_shrub",				"kasi lili pi telo ala"},
	{"default:grass_1",				"kasi anpa"},
	{"default:grass_2",				"kasi anpa"},
	{"default:grass_3",				"kasi anpa"},
	{"default:grass_4",				"kasi anpa"},
	{"default:grass_5",				"kasi anpa"},
	{"default:ice",					"telo kiwen"},
	{"default:snow",				"ko lete"},
	{"default:snowblock",				"ko lete suli"},
	-- tools
	{"default:pick_wood",				"ilo pi alasa kiwen pi sijelo kasi"},
	{"default:pick_stone",				"ilo kiwen pi alasa kiwen"},
	{"default:pick_copper",				"ilo pi alasa kiwen pi kiwen pimeja loje"},
	{"default:pick_steel",				"ilo pi alasa kiwen pi kiwen walo"},
	{"default:pick_mese",				"ilo pi alasa kiwen pi kiwen nasa"},
	{"default:shovel_wood",				"ilo pi alasa ma pi sijelo kasi"},
	{"default:shovel_stone",			"ilo kiwen pi alasa ma"},
	{"default:shovel_copper",			"ilo pi alasa ma pi kiwen pimeja loje"},
	{"default:shovel_steel",			"ilo pi alasa ma pi kiwen walo"},
	{"default:axe_wood",				"ilo pi alasa kasi pi sijelo kasi"},
	{"default:axe_stone",				"ilo kiwen pi alasa kasi"},
	{"default:axe_copper",				"ilo pi alasa kiwen pi kiwen pimeja loje"},
	{"default:axe_steel",				"ilo pi alasa kiwen pi kiwe walo"},
	{"default:sword_wood",				"ilo utala pi sijelo kasi"},
	{"default:sword_stone",				"ilo utala kiwen"},
	{"default:sword_copper",			"ilo utala pi kiwen pimeja loje"},
	{"default:sword_steel",				"ilo utala pi kiwen walo"},
	
	-- doors
	{"doors:door_wood",				"lupa tomo"},
	{"doors:door_steel",				"lupa tomo pi kiwen walo"},
	
	-- dye
	{"dye:white",					"kule walo"},
	{"dye:grey",					"kule walo pimeja"},
	{"dye:dark_grey",				"kule pimeja walo"},
	{"dye:black",					"kule pimeja"},
	{"dye:violet",					"kule laso loje"},
	{"dye:blue",					"kule laso"},
	{"dye:cyan",					"kule laso jelo"},
	{"dye:dark_green",				"kule jelo kasi pimeja"},
	{"dye:green",					"kule jelo kasi"},
	{"dye:yellow",					"kule jelo"},
	{"dye:brown",					"kule pi ma jaki"},
	{"dye:orange",					"kule jelo loje"},
	{"dye:red",					"kule loje"},
	{"dye:magenta",					"kule loje laso"},
	{"dye:pink",					"kule loje laso pi jelo ala"},
	
	-- farming
	{"farming:soil",				"ma kasi"},
	{"farming:soil_wet",				"ma kasi telo"},
	{"farming:seed_cotton",				"sike lili pi kasi pi kiwen ala"},
	{"farming:cotton",				"kasi pi kiwen ala"},
	{"farming:cotton_1",				"kasi pi kiwen ala"},
	{"farming:cotton_2",				"kasi pi kiwen ala"},
	{"farming:cotton_3",				"kasi pi kiwen ala"},
	{"farming:cotton_4",				"kasi pi kiwen ala"},
	{"farming:cotton_5",				"kasi pi kiwen ala"},
	{"farming:string",				"linja"},
	{"farming:hoe_wood",				"ilo pi ma kasi"},
	{"farming:hoe_stone",				"ilo kiwen pi ma kasi"},
	{"farming:hoe_steel",				"ilo pi kiwen walo pi ma kasi"},
	{"farming:hoe_bronze",				"ilo pi kiwen jelo loje pi ma kasi"},
	{"farming:hoe_mese",				"ilo pi kiwen nasa pi ma kasi"},
	{"farming:weed",				"kasi ike"},
	{"farming:seed_wheat",				"sike lili pi kasi pan"},
	{"farming:wheat",				"pan"},
	{"farming:wheat_1",				"pan"},
	{"farming:wheat_2",				"pan"},
	{"farming:wheat_3",				"pan"},
	{"farming:wheat_4",				"pan"},
	{"farming:wheat_5",				"pan"},
	{"farming:wheat_6",				"pan"},
	{"farming:wheat_7",				"pan"},
	{"farming:wheat_8",				"pan"},
	{"farming:flour",				"ko lili pan"},
	{"farming:dough",				"ko pan"},
	{"farming:bread",				"pan moku"},
	
	-- fire
	{"fire:basic_flame",				"seli"},
	
	-- flowers
	{"flowers:dandelion_white",			"kasi walo"},
	{"flowers:dandelion_yellow",			"kasi jelo"},
	{"flowers:geranium",				"kasi laso"},
	{"flowers:rose",				"kasi loje"},
	{"flowers:tulip",				"kasi jelo loje"},
	{"flowers:viola",				"kasi laso loje"},
	
	-- nodetest
	{"nodetest:bone",				"palisa pi jan moli"},
	{"nodetest:desert_sandstone",			"kiwen loje pi ko kiwen"},
	{"nodetest:rock",				"kiwen kiwen"},
	{"nodetest:tree_horizontal",			"kasi lape"},
	{"nodetest:jungletree_horizontal",		"kasi lape pi ma pi kasi mute"},
	{"nodetest:papyrus_roots",			"noka pi kasi lipu"},
	{"nodetest:conifersapling",			"kasi lili pi kasi suli"},
	{"nodetest:conifertree",			"kasi suli"},
	{"nodetest:coniferleaves_1",			"lipu pi kasi suli"},
	{"nodetest:coniferleaves_2",			"lipu pi kasi suli"},
	{"nodetest:conifertree_horizontal",		"kasi suli lape"},
	{"nodetest:spearwood",				"palisa kasi"},
	{"nodetest:spearstone",				"palisa kiwen"},
	
	-- pots
	{"pots:pot",					"poki kasi"},
	{"pots:cactus",					"poki pi kasi pi palisa lili"},
	{"pots:dandelion_white",			"poki pi kasi walo"},
	{"pots:dandelion_yellow",			"poki pi kasi jelo"},
	{"pots:geranium",				"poki pi kasi laso"},
	{"pots:rose",					"poki pi kasi loje"},
	{"pots:tulip",					"poki pi kasi jelo loje"},
	{"pots:viola",					"poki pi kasi loje laso"},
	
	-- screwdriver
	{"screwdriver:screwdriver",			"ilo sike"},
	{"screwdriver:screwdriver1",			"ilo sike"},
	{"screwdriver:screwdriver2",			"ilo sike"},
	{"screwdriver:screwdriver3",			"ilo sike"},
	{"screwdriver:screwdriver4",			"ilo sike"},
	
	-- wool
	{"wool:white",					"len walo"},
	{"wool:grey",					"len walo pimeja"},
	{"wool:dark_grey",				"len walo pimeja pimeja"},
	{"wool:black",					"len pimeja"},
	{"wool:violet",					"len laso loje"},
	{"wool:blue",					"len laso"},
	{"wool:cyan",					"len laso walo"},
	{"wool:dark_green",				"len jelo laso pimeja"},
	{"wool:green",					"len jelo laso"},
	{"wool:yellow",					"len jelo"},
	{"wool:brown",					"len pi kule ma"},
	{"wool:orange",					"len jelo loje"},
	{"wool:red",					"len loje"},
	{"wool:magenta",				"len loje laso"},
	{"wool:pink",					"len loje walo"},

	-- vessels
	{"vessels:glass_bottle",			"poki pi kule ala"},
	{"vessels:drinking_glass",			"poki telo pi kule ala"},
	{"vessels:steel_bottle",			"poki pi kiwen walo"},
	{"vessels:glass_fragments",			"kiwen lili pi poki pi kule ala"},
}
