----
-- Türkçeleştiren mahmutelmas06@hotmail.com
----
-- Licence for this file and translations: CC0

return {
	-- beds
	{"beds:bed",					"Yatak"},

	-- bones
	{"bones:bones",					"Kemikler"},
	
	-- bucket
	{"bucket:bucket_empty",				"Boş kova"},
	{"bucket:bucket_water",				"Su kovası"},
	{"bucket:bucket_lava",				"Lav kovası"},

	-- carts
	{"carts:cart",					"Vagon"},
	{"carts:powerrail",				"Elektrikli ray"},
	{"carts:brakerail",				"Yavaşlatma rayı"},
	
	-- default
	-- craftitems
	{"default:stick",					"Çubuk"},
	{"default:paper",					"Kağıt"},
	{"default:book",					"Kitap"},
	{"default:coal_lump",				"Kömür yığını"},
	{"default:iron_lump",				"Demir yığını"},
	{"default:copper_lump",				"Bakır yığını"},
	{"default:mese_crystal",				"Mese kristali"},
	{"default:gold_lump",				"Altın yığını"},
	{"default:diamond",					"Elmas"},
	{"default:clay_lump",				"Kil yığını"},
	{"default:steel_ingot",				"Çelik yığını"},
	{"default:copper_ingot",				"Bakır külçesi"},
	{"default:bronze_ingot",				"Bronz külçesi"},
	{"default:gold_ingot",				"Altın külçesi"},
	{"default:mese_crystal_fragment",		"Mese kristalcikleri"},
	{"default:clay_brick",				"Kil tuğlası"},
	{"default:scorched_stuff",			"Yanmış şeyler"},
	{"default:obsidian_shard",			"Camkaya kırığı"},
	-- nodes
	{"default:stone",					"Taş"},
	{"default:desert_stone",				"Çöl taşı"},
	{"default:stone_with_coal",			"Kömürlü taş"},
	{"default:stone_with_iron",			"Demirli taş"},
	{"default:stone_with_copper",			"Bakırlı taş"},
	{"default:stone_with_mese",			"Meseli taş"},
	{"default:stone_with_gold",			"Altınlı taş"},
	{"default:stone_with_diamond",		"Elmaslı taş"},
	{"default:stone_stonebrick",			"Taş tuğla"},
	{"default:stone_desert_stonebrick",	"Çöl Toprağından Tuğla"},
	{"default:dirt_with_grass",			"Otlu toprak"},
	{"default:dirt_with_grass_footsteps",	"Çimende ayak izleri"},
	{"default:dirt_with_snow",			"Ot üzeri kar"},
	{"default:dirt",					"Toprak"},
	{"default:sand",					"Kum"},
	{"default:desert_sand",				"Çöl kumu"},
	{"default:gravel",					"Çakıl"},
	{"default:sandstone",				"Kum taşı"},
	{"default:sandstonebrick",			"Kum taşından tuğla"},
	{"default:clay",					"Kil"},
	{"default:brick",					"Tuğla"},
	{"default:tree",					"Ağaç"},
	{"default:jungletree",				"Orman Ağacı"},
	{"default:junglewood",				"Orman odunu"},
	{"default:jungleleaves",				"Orman Yapraklar"},
	{"default:junglesapling",			"Orman Ağacı Fidanı"},
	{"default:junglegrass",				"Orman çimi"},
	{"default:leaves",					"Yapraklar"},
	{"default:cactus",					"Kaktüs"},
	{"default:papyrus",					"Papirüs"},
	{"default:bookshelf",				"Kitaplık"},
	{"default:glass",					"Cam"},
	{"default:fence_wood",				"Çit"},
	{"default:rail",					"Ray"},
	{"default:ladder",					"Merdiven"},
	{"default:wood",					"Odun"},
	{"default:cloud",					"Bulut"},
	{"default:water_flowing",			"Akan su"},
	{"default:water_source",				"Su kaynağı"},
	{"default:lava_flowing",				"Akan lav"},
	{"default:lava_source",				"Lav kaynağı"},
	{"default:torch",					"Meşale"},
	{"default:sign_wall",				"Tabela"},
	{"default:chest",					"Sandık"},
	{"default:chest_locked",				"Kilitli sandık"},
	{"default:furnace",					"Fırın"},
	{"default:furnace_active",			"Yanan fırın"},
	{"default:cobble",					"Kaldırım taşı"},
	{"default:mossycobble",				"Yosunlu kaldırım taşı"},
	{"default:coalblock",				"Kömür bloğu"},
	{"default:steelblock",				"Çelik blok"},
	{"default:copperblock",				"Bakır blok"},
	{"default:bronzeblock",				"Bronz blok"},
	{"default:mese",					"Mese"},
	{"default:goldblock",				"Altın blok"},
	{"default:diamondblock",				"Elmas blok"},
	{"default:obsidian_glass",			"Camkaya camı"},
	{"default:obsidian",				"Camkaya"},
	{"default:nyancat",					"Pisicik"},
	{"default:nyancat_rainbow",			"Pisicik gökkuşağı"},
	{"default:sapling",					"Fide"},
	{"default:apple",					"Elma"},
	{"default:dry_shrub",				"Kuru çalı"},
	{"default:grass_1",					"Çimen 1"},
	{"default:grass_2",					"Çimen 2"},
	{"default:grass_3",					"Çimen 3"},
	{"default:grass_4",					"Çimen 4"},
	{"default:grass_5",					"Çimen 5"},
	{"default:ice",					"Buz"},
	{"default:snow",					"Kar"},
	{"default:snowblock",				"Kar bloğu"},
	-- tools
	{"default:pick_wood",				"Ahşap kazma"},
	{"default:pick_stone",				"Taş kazma"},
	{"default:pick_copper",				"Bakır kazma"},
	{"default:pick_steel",				"Çelik kazma"},
	{"default:pick_mese",				"Mese kazma"},
	{"default:shovel_wood",				"Ahşap kürek"},
	{"default:shovel_stone",				"Taş kürek"},
	{"default:shovel_copper",			"Bakır kürek"},
	{"default:shovel_steel",				"Çelik kürek"},
	{"default:axe_wood",				"Ahşap balta"},
	{"default:axe_stone",				"Taş balta"},
	{"default:axe_copper",				"Bakır balta"},
	{"default:axe_steel",				"Çelik balta"},
	{"default:sword_wood",				"Ahşap kılıç"},
	{"default:sword_stone",				"Taş kılıç"},
	{"default:sword_copper",				"Bakır kılıç"},
	{"default:sword_steel",				"Çelik kılıç"},
	
	-- doors
	{"doors:door_wood",					"Ağaç kapı"},
	{"doors:door_steel",				"Çelik kapı"},
	
	-- dye
	{"dye:white",						"Beyaz"},
	{"dye:grey",						"Gri"},
	{"dye:dark_grey",					"Koyu Gri"},
	{"dye:black",						"Siyah"},
	{"dye:violet",						"Mor"},
	{"dye:blue",						"Mavi"},
	{"dye:cyan",						"Çiyan"},
	{"dye:dark_green",					"Koyu yeşil"},
	{"dye:green",						"Yeşil"},
	{"dye:yellow",						"Sarı"},
	{"dye:brown",						"Kahverengi"},
	{"dye:orange",						"Turuncu"},
	{"dye:red",						"Kırmızı"},
	{"dye:magenta",					"Lila"},
	{"dye:pink",						"Pembe"},
	
	-- farming
	{"farming:soil",					"Toprak"},
	{"farming:soil_wet",				"Islak toprak"},
	{"farming:seed_cotton",				"Pamuk tohumu"},
	{"farming:cotton",					"Tohum"},
	{"farming:cotton_1",				"Tohum 1"},
	{"farming:cotton_2",				"Tohum 2"},
	{"farming:cotton_3",				"Tohum 3"},
	{"farming:cotton_4",				"Tohum 4"},
	{"farming:cotton_5",				"Tohum 5"},
	{"farming:string",					"Sicim"},
	{"farming:hoe_wood",				"Ahşap çapa"},
	{"farming:hoe_stone",				"Taş çapa"},
	{"farming:hoe_steel",				"Çelik çapa"},
	{"farming:hoe_bronze",				"Bronz çapa"},
	{"farming:hoe_mese",				"Mese çapa"},
	{"farming:weed",					"Ot"},
	{"farming:seed_wheat",				"Buğday tohumu"},
	{"farming:wheat",					"Buğday"},
	{"farming:wheat_1",					"Buğday 1"},
	{"farming:wheat_2",					"Buğday 2"},
	{"farming:wheat_3",					"Buğday 3"},
	{"farming:wheat_4",					"Buğday 4"},
	{"farming:wheat_5",					"Buğday 5"},
	{"farming:wheat_6",					"Buğday 6"},
	{"farming:wheat_7",					"Buğday 7"},
	{"farming:wheat_8",					"Buğday 8"},
	{"farming:flour",					"Un"},
	{"farming:dough",					"Hamur"},
	{"farming:bread",					"Ekmek"},
	
	-- fire
	{"fire:basic_flame",				"Kıvılcım"},
	
	-- flowers
	{"flowers:dandelion_white",			"Beyaz hindiba"},
	{"flowers:dandelion_yellow",			"Sarı hindiba"},
	{"flowers:geranium",				"Sardunya"},
	{"flowers:rose",					"Gül"},
	{"flowers:tulip",					"Karanfil"},
	{"flowers:viola",					"Menekşe"},
	
	-- pots
--	{"pots:pot",						""},
--	{"pots:cactus",					""},
--	{"pots:dandelion_white",				""},
--	{"pots:dandelion_yellow",			""},
--	{"pots:geranium",					""},
--	{"pots:rose",						""},
--	{"pots:tulip",						""},
--	{"pots:viola",						""},
	
	-- screwdriver
	{"screwdriver:screwdriver",			"Tornavida"},
--	{"screwdriver:screwdriver1",			"Tornavida 1"},
--	{"screwdriver:screwdriver2",			"Tornavida 2"},
--	{"screwdriver:screwdriver3",			"Tornavida 3"},
--	{"screwdriver:screwdriver4",			"Tornavida 4"},
	
	-- wool
	{"wool:white",						"Beyaz yün"},
	{"wool:grey",						"Gri yün"},
	{"wool:dark_grey",					"Koyu gri yün"},
	{"wool:black",						"Siyah yün"},
	{"wool:violet",					"Mor yün"},
	{"wool:blue",						"Mavi yün"},
	{"wool:cyan",						"Çiyan yün"},
	{"wool:dark_green",					"Koyu yeşil yün"},
	{"wool:green",						"Yeşil yün"},
	{"wool:yellow",					"Sarı yün"},
	{"wool:brown",						"Kahverengi yün"},
	{"wool:orange",					"Turuncu yün"},
	{"wool:red",						"Kırmızı yün"},
	{"wool:magenta",					"Lila yün"},
	{"wool:pink",						"Pembe yün"},

	-- vessels
	{"vessels:glass_bottle",				"Boş şişe"},
	{"vessels:drinking_glass",			"Bardak"},
	{"vessels:steel_bottle",				"Çelik şişe"},
	{"vessels:glass_fragments",			"Cam parçaları"},
	
	-- Protector Redo
	{"protector:protect",				"Koruma Kutusu"},
	{"protector:protect2",				"Koruma Arması"},
	{"protector:door_wood",				"Korumalı Ağaç Kapı"},
	{"protector:door_steel",				"Korumalı Çelik Kapı"},
	{"protector:chest",					"Korumalı Sandık"},
}
